import random
import hashlib

FIRST_NAMES = [
    'James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda',
    'William', 'Barbara', 'David', 'Elizabeth', 'Richard', 'Susan', 'Joseph', 'Jessica',
    'Thomas', 'Sarah', 'Charles', 'Karen', 'Christopher', 'Lisa', 'Daniel', 'Nancy',
    'Matthew', 'Betty', 'Anthony', 'Margaret', 'Mark', 'Sandra', 'Donald', 'Ashley',
    'Steven', 'Dorothy', 'Paul', 'Kimberly', 'Andrew', 'Emily', 'Joshua', 'Donna',
    'Kenneth', 'Michelle', 'Kevin', 'Carol', 'Brian', 'Amanda', 'George', 'Melissa',
    'Timothy', 'Deborah', 'Ronald', 'Stephanie', 'Edward', 'Rebecca', 'Jason', 'Sharon',
    'Jeffrey', 'Laura', 'Ryan', 'Cynthia', 'Jacob', 'Kathleen', 'Gary', 'Amy',
    'Nicholas', 'Angela', 'Eric', 'Shirley', 'Jonathan', 'Anna', 'Stephen', 'Brenda',
    'Larry', 'Pamela', 'Justin', 'Emma', 'Scott', 'Nicole', 'Brandon', 'Helen',
    'Benjamin', 'Samantha', 'Samuel', 'Katherine', 'Raymond', 'Christine', 'Gregory',
    'Debra', 'Frank', 'Rachel', 'Alexander', 'Carolyn', 'Patrick', 'Janet', 'Jack',
    'Catherine', 'Dennis', 'Maria', 'Jerry', 'Heather', 'Tyler', 'Diane', 'Aaron',
    'Julie', 'Jose', 'Joyce', 'Adam', 'Victoria', 'Nathan', 'Kelly', 'Henry',
    'Christina', 'Douglas', 'Lauren', 'Zachary', 'Joan', 'Peter', 'Evelyn', 'Kyle',
    'Olivia', 'Walter', 'Judith', 'Ethan', 'Megan', 'Jeremy', 'Cheryl', 'Harold',
    'Andrea', 'Terry', 'Hannah', 'Sean', 'Martha', 'Austin', 'Jacqueline', 'Carl',
    'Frances', 'Arthur', 'Gloria', 'Lawrence', 'Ann', 'Dylan', 'Teresa', 'Jesse',
    'Kathryn', 'Jordan', 'Sara', 'Bryan', 'Janice', 'Billy', 'Jean', 'Bruce',
    'Alice', 'Gabriel', 'Madison', 'Joe', 'Doris', 'Logan', 'Abigail', 'Alan',
    'Julia', 'Juan', 'Judy', 'Albert', 'Rose', 'Willie', 'Grace', 'Wayne',
    'Denise', 'Randy', 'Amber', 'Mason', 'Marilyn', 'Roy', 'Beverly', 'Ralph',
    'Danielle', 'Eugene', 'Theresa', 'Russell', 'Sophia', 'Bobby', 'Marie',
    # additional diverse names
    'Aisha', 'Priya', 'Wei', 'Mei', 'Fatima', 'Amara', 'Yuki', 'Leila',
    'Ananya', 'Zara', 'Nadia', 'Ingrid', 'Astrid', 'Brigitte', 'Colette',
    'Daphne', 'Elise', 'Fiona', 'Gwendolyn', 'Helena', 'Isadora', 'Josephine',
    'Kieran', 'Liam', 'Niall', 'Ronan', 'Cormac', 'Declan', 'Fergus', 'Seamus',
    'Arjun', 'Vikram', 'Rahul', 'Nikhil', 'Ravi', 'Sanjay', 'Deepak', 'Amit',
    'Omar', 'Tariq', 'Hassan', 'Khalid', 'Ibrahim', 'Yousef', 'Faisal', 'Nasser',
    'Diego', 'Mateo', 'Alejandro', 'Sebastian', 'Ricardo', 'Fernando', 'Carlos', 'Miguel',
    'Elena', 'Isabel', 'Valentina', 'Camila', 'Lucia', 'Sofia', 'Gabriela', 'Catalina',
    'Hiroshi', 'Kenji', 'Takeshi', 'Naoki', 'Shinji', 'Haruto', 'Ren', 'Yuto',
    'Akiko', 'Yumi', 'Keiko', 'Naomi', 'Haruki', 'Sakura', 'Aiko', 'Emi',
    'Chidi', 'Emeka', 'Obinna', 'Adebayo', 'Oluwaseun', 'Nnamdi', 'Chisom', 'Ifeoma',
    'Kofi', 'Kwame', 'Ama', 'Abena', 'Yaw', 'Efua', 'Nana', 'Akosua',
    'Andrei', 'Dmitri', 'Pavel', 'Nikolai', 'Alexei', 'Sergei', 'Mikhail', 'Boris',
    'Anastasia', 'Natasha', 'Irina', 'Olga', 'Tatiana', 'Svetlana', 'Ekaterina',
    'Henrik', 'Lars', 'Bjorn', 'Erik', 'Magnus', 'Sven', 'Gunnar', 'Torsten',
    'Annika', 'Sigrid', 'Freya', 'Solveig', 'Maja', 'Lena', 'Hanna', 'Karin',
    'Amir', 'Darius', 'Cyrus', 'Xerxes', 'Reza', 'Mehdi', 'Navid', 'Shervin',
    'Aroha', 'Tane', 'Hemi', 'Rangi', 'Wiremu', 'Aroha', 'Mere', 'Hine',
    'Cameron', 'Callum', 'Ewan', 'Angus', 'Hamish', 'Alistair', 'Iain', 'Rory',
    'Fionnuala', 'Siobhan', 'Aoife', 'Niamh', 'Caoimhe', 'Aisling', 'Ciara', 'Grainne',
    # More American/English given names — classic
    'Theodore', 'Frederick', 'Leonard', 'Chester', 'Herbert', 'Ernest', 'Clifford',
    'Vernon', 'Luther', 'Harvey', 'Virgil', 'Dewey', 'Elmer', 'Otis', 'Lloyd',
    'Cecil', 'Percy', 'Horace', 'Wilbur', 'Bert', 'Gus', 'Hal', 'Ned', 'Walt',
    'Silas', 'Ezra', 'Amos', 'Eli', 'Seth', 'Abel', 'Beau', 'Clint', 'Drew',
    'Glen', 'Rex', 'Ross', 'Bret', 'Wade', 'Bart', 'Dwight', 'Earl', 'Hugh',
    'Lane', 'Lyle', 'Neil', 'Reed', 'Dale', 'Gene', 'Glenn', 'Kent', 'Leroy',
    'Lowell', 'Merle', 'Monty', 'Norma', 'Peggy', 'Phyllis', 'Vera',
    'Viola', 'Virginia', 'Wilma', 'Winifred', 'Gail', 'Hazel', 'Ida', 'Inez',
    'Irene', 'Iris', 'Ivy', 'Lola', 'Loretta', 'Lorraine', 'Lucille', 'Lucy',
    'Mae', 'Marjorie', 'Marlene', 'Mildred', 'Minnie', 'Molly', 'Myrtle', 'Nora',
    'Opal', 'Pearl', 'Reba', 'Rhonda', 'Rita', 'Roberta', 'Rosa', 'Ruby',
    'Sally', 'Selma', 'Sheila', 'Sherry', 'Sybil', 'Sylvia', 'Eloise', 'Loretta',
    # Modern American female names
    'Alexis', 'Allison', 'Alyssa', 'April', 'Ariel', 'Autumn', 'Avery',
    'Bella', 'Beth', 'Brianna', 'Brittany', 'Brooke', 'Chelsea',
    'Chloe', 'Claire', 'Courtney', 'Crystal', 'Daisy', 'Dana', 'Dawn',
    'Destiny', 'Ella', 'Eva', 'Faith', 'Gabrielle', 'Hailey', 'Hope',
    'Jade', 'Jamie', 'Jasmine', 'Jenna', 'Kayla', 'Kelsey', 'Kristen',
    'Kylie', 'Lacey', 'Leah', 'Lindsay', 'Makena', 'Maya', 'Miranda',
    'Morgan', 'Natalie', 'Paige', 'Reagan', 'Savannah', 'Sierra', 'Skylar',
    'Summer', 'Tara', 'Tiffany', 'Tina', 'Tracey', 'Whitney', 'Zoe',
    'Aaliyah', 'Addison', 'Aurora', 'Brielle', 'Camille', 'Demi', 'Eliana',
    'Fallon', 'Gianna', 'Harper', 'Isla', 'Jordyn', 'Kendall', 'Layla',
    'Mariah', 'Nadia', 'Payton', 'Quinn', 'Riley', 'Sloane', 'Teagan',
    'Valentina', 'Waverly', 'Xiomara', 'Yareli', 'Zoey',
    # Modern American male names
    'Barry', 'Brad', 'Bradley', 'Brett', 'Caleb', 'Cameron', 'Chad',
    'Charlie', 'Clayton', 'Cody', 'Colin', 'Craig', 'Curtis', 'Dalton',
    'Damian', 'Derek', 'Derrick', 'Dillon', 'Dwayne', 'Eddie', 'Elliot',
    'Evan', 'Garrett', 'Gavin', 'Gordon', 'Grant', 'Hunter', 'Ian',
    'Jake', 'Jared', 'Jay', 'Joel', 'Julian', 'Keith', 'Lance', 'Marcus',
    'Max', 'Miles', 'Mitchell', 'Nolan', 'Parker', 'Preston', 'Quinn',
    'Randall', 'Ricky', 'Rob', 'Shane', 'Shawn', 'Spencer', 'Stan',
    'Tanner', 'Travis', 'Trevor', 'Troy', 'Victor', 'Vincent',
    'Warren', 'Wesley', 'Will', 'Xavier', 'Zach', 'Colin', 'Finn', 'Levi',
    'Micah', 'Owen', 'Sawyer', 'Silas', 'Tobias', 'Tristan', 'Wyatt',
    # Chinese given names (romanized)
    'Bao', 'Chang', 'Feng', 'Hao', 'Jian', 'Jing', 'Jun', 'Lei',
    'Liang', 'Lin', 'Ming', 'Ping', 'Qian', 'Qing', 'Rui', 'Sheng',
    'Shu', 'Ting', 'Wen', 'Xia', 'Xiao', 'Xin', 'Yan', 'Yi',
    'Ying', 'Yong', 'Yuan', 'Zhen', 'Zheng', 'Zhi', 'Zhong', 'Zhu',
    'Chenxi', 'Fangfang', 'Guoqiang', 'Jiaming', 'Lihua', 'Minghao',
    'Ruoxi', 'Tingting', 'Weiwei', 'Xiaoming', 'Yifei', 'Zijian',
    # Korean given names
    'Bomi', 'Chaeyoung', 'Eunji', 'Hana', 'Hyunjin', 'Jiyeon', 'Minji',
    'Seojun', 'Soyeon', 'Subin', 'Taehyun', 'Yunho', 'Minho', 'Jieun',
    'Doyeon', 'Heejin', 'Hyeri', 'Jiwon', 'Nayeon', 'Seungmin', 'Yeonwoo',
    # Additional Indian given names
    'Aditya', 'Anjali', 'Ankit', 'Ankita', 'Ashish', 'Bhavna', 'Divya',
    'Gaurav', 'Harish', 'Kavya', 'Kiran', 'Manish', 'Meenakshi', 'Mohan',
    'Neeraj', 'Pooja', 'Prakash', 'Preeti', 'Puneet', 'Rekha', 'Rohit',
    'Sangeeta', 'Satish', 'Shilpa', 'Shruti', 'Sunita', 'Suresh', 'Swati',
    'Varun', 'Vinay', 'Vivek', 'Balakrishnan', 'Venkatesh',
    'Radhika', 'Sudha', 'Lalitha', 'Meera', 'Vani', 'Savita', 'Usha',
    'Abhishek', 'Chirag', 'Dhruv', 'Ishaan', 'Kartik', 'Kunal', 'Lakshmi',
    'Neha', 'Pallavi', 'Ruchika', 'Shubham', 'Tanvi', 'Tushar', 'Vidya',
    # Arabic / Middle Eastern given names
    'Abdulaziz', 'Abdulrahman', 'Abdullah', 'Hessa', 'Layla', 'Lina',
    'Maha', 'Maryam', 'Munira', 'Noura', 'Rania', 'Rim', 'Samar',
    'Wafaa', 'Yasmin', 'Zainab', 'Hamza', 'Mustafa', 'Bilal', 'Anas',
    'Mariam', 'Amal', 'Hind', 'Suha', 'Reem', 'Dina', 'Nour', 'Rana',
    'Adnan', 'Bassam', 'Emad', 'Ghassan', 'Imad', 'Jassim', 'Khaled',
    'Lubna', 'Maan', 'Nadine', 'Osama', 'Rami', 'Samia', 'Tariq',
    # West African given names
    'Adaeze', 'Adaobi', 'Adeola', 'Adenike', 'Adesola', 'Adewale',
    'Afia', 'Akintunde', 'Aminu', 'Ayo', 'Babatunde', 'Chidinma',
    'Chika', 'Chinonso', 'Chinyere', 'Chioma', 'Ekene', 'Folake',
    'Funmilayo', 'Gift', 'Hadiza', 'Hauwa', 'Ifeanyi', 'Ike',
    'Kemi', 'Kola', 'Kunle', 'Ladi', 'Lawal', 'Ndidi', 'Ngozi',
    'Nkechi', 'Nneka', 'Odunayo', 'Olanrewaju', 'Oluwafemi',
    'Oluwakemi', 'Oluwasegun', 'Onyinye', 'Opeyemi', 'Patience',
    'Peace', 'Precious', 'Rotimi', 'Seun', 'Sola', 'Temitope',
    'Titi', 'Tobi', 'Tochukwu', 'Toyin', 'Uche', 'Ugochi',
    'Yetunde', 'Chiamaka', 'Chukwuemeka', 'Obiageli', 'Princewill',
    'Adebimpe', 'Adefunke', 'Adeyinka', 'Akanni', 'Amaka', 'Biola',
    'Damilola', 'Emem', 'Ibeji', 'Jide', 'Kehinde', 'Modupe', 'Remi',
    # Latin American given names
    'Adriana', 'Agustin', 'Alberto', 'Alicia', 'Amparo',
    'Angelica', 'Beatriz', 'Brenda', 'Carmen', 'Cecilia', 'Claudia',
    'Cristina', 'Eduardo', 'Enrique', 'Estela', 'Flor', 'Francisco',
    'Gloria', 'Graciela', 'Guillermo', 'Hector', 'Ignacio',
    'Liliana', 'Lorena', 'Luciana', 'Luis', 'Magdalena', 'Marcela',
    'Marco', 'Monica', 'Nicolas', 'Paula', 'Rafael', 'Raquel',
    'Roberto', 'Rodrigo', 'Silvia', 'Susana', 'Teresa', 'Veronica',
    'Ximena', 'Yanira', 'Yolanda', 'Andres', 'Carla', 'Daniela',
    'Ernesto', 'Fabiana', 'Gonzalo', 'Horacio', 'Jimena', 'Leandro',
    'Marisol', 'Natalia', 'Orlando', 'Pilar', 'Romina', 'Santiago',
    # European given names
    'Adelheid', 'Aleksander', 'Aleksandra', 'Alessio', 'Alicja',
    'Antonia', 'Attila', 'Baptiste', 'Benedikt', 'Birgit',
    'Bogdan', 'Brigitte', 'Bruno', 'Claudine', 'Cristian', 'Dagmar',
    'Dorota', 'Edith', 'Eleonora', 'Emilia', 'Emilio', 'Erika',
    'Fabio', 'Florian', 'Franz', 'Friederike', 'Gabriele', 'Georg',
    'Gerhard', 'Giovanna', 'Giuseppe', 'Gregor', 'Hans', 'Hannelore',
    'Heidi', 'Helga', 'Horst', 'Ines', 'Inge', 'Irena', 'Jochen',
    'Johann', 'Josef', 'Juergen', 'Kaarina', 'Kaja', 'Katarzyna',
    'Katja', 'Klaus', 'Konrad', 'Laszlo', 'Lorenzo', 'Luca',
    'Lukas', 'Margit', 'Marianna', 'Mario', 'Marta', 'Matthias',
    'Miriam', 'Monika', 'Nils', 'Oskar', 'Otto', 'Petra', 'Pietro',
    'Ralf', 'Regina', 'Renate', 'Rolf', 'Ryszard', 'Sabine',
    'Sigrid', 'Stefan', 'Stefanie', 'Susanne', 'Tobias', 'Ulrike',
    'Ute', 'Veronika', 'Wilhelm', 'Wolfgang', 'Zbigniew',
    'Agnieszka', 'Bartosz', 'Dorota', 'Filip', 'Grzegorz', 'Henryk',
    'Jadwiga', 'Krzysztof', 'Marek', 'Pawel', 'Stanislaw', 'Tadeusz',
    'Elias', 'Elisabetta', 'Francesca', 'Gianfranco', 'Ilaria', 'Jacopo',
    'Manuela', 'Nicola', 'Paola', 'Raffaele', 'Serena', 'Valentina',
    # Pacific / Maori names
    'Aroha', 'Tane', 'Hemi', 'Rangi', 'Wiremu', 'Mere', 'Hine',
    'Tamati', 'Reweti', 'Hinewai', 'Mairangi', 'Kahu', 'Piripi',
]

LAST_NAMES = [
    'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis',
    'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson',
    'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin', 'Lee', 'Perez', 'Thompson',
    'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson', 'Walker',
    'Young', 'Allen', 'King', 'Wright', 'Scott', 'Torres', 'Nguyen', 'Hill', 'Flores',
    'Green', 'Adams', 'Nelson', 'Baker', 'Hall', 'Rivera', 'Campbell', 'Mitchell',
    'Carter', 'Roberts', 'Turner', 'Phillips', 'Evans', 'Collins', 'Stewart',
    'Morris', 'Rogers', 'Reed', 'Cook', 'Morgan', 'Bell', 'Murphy', 'Bailey',
    'Cooper', 'Richardson', 'Cox', 'Howard', 'Ward', 'Peterson', 'Gray',
    'James', 'Watson', 'Brooks', 'Kelly', 'Sanders', 'Price', 'Bennett',
    'Wood', 'Barnes', 'Ross', 'Henderson', 'Coleman', 'Jenkins', 'Perry', 'Powell',
    'Long', 'Patterson', 'Hughes', 'Washington', 'Butler', 'Simmons',
    'Foster', 'Gonzales', 'Bryant', 'Alexander', 'Russell', 'Griffin', 'Diaz',
    'Hayes', 'Myers', 'Ford', 'Hamilton', 'Graham', 'Sullivan', 'Wallace', 'Woods',
    'Cole', 'West', 'Jordan', 'Owens', 'Reynolds', 'Fisher', 'Ellis', 'Harrison',
    'Gibson', 'Mcdonald', 'Cruz', 'Marshall', 'Ortiz', 'Gomez', 'Murray', 'Freeman',
    'Wells', 'Webb', 'Simpson', 'Stevens', 'Tucker', 'Porter', 'Hunter', 'Hicks',
    'Crawford', 'Henry', 'Boyd', 'Mason', 'Morales', 'Kennedy', 'Warren', 'Dixon',
    'Ramos', 'Reyes', 'Burns', 'Gordon', 'Shaw', 'Holmes', 'Rice', 'Robertson',
    'Hunt', 'Black', 'Daniels', 'Palmer', 'Mills', 'Nichols', 'Grant', 'Knight',
    'Ferguson', 'Rose', 'Stone', 'Hawkins', 'Dunn', 'Perkins', 'Hudson', 'Spencer',
    'Gardner', 'Stephens', 'Payne', 'Pierce', 'Berry', 'Matthews', 'Arnold', 'Wagner',
    'Willis', 'Ray', 'Watkins', 'Moreno', 'Snyder', 'Hoover', 'Townsend', 'Medina',
    # additional diverse surnames
    'Patel', 'Shah', 'Kumar', 'Singh', 'Sharma', 'Gupta', 'Mehta', 'Chopra',
    'Nakamura', 'Yamamoto', 'Tanaka', 'Watanabe', 'Suzuki', 'Ito', 'Kato', 'Kobayashi',
    'Kim', 'Park', 'Choi', 'Yoon', 'Lim', 'Jung', 'Kwon', 'Shin',
    'Chen', 'Wang', 'Zhang', 'Liu', 'Yang', 'Huang', 'Zhou', 'Wu',
    'Okafor', 'Adeyemi', 'Nwosu', 'Obi', 'Eze', 'Chukwu', 'Nwachukwu', 'Okonkwo',
    'Mensah', 'Asante', 'Boateng', 'Owusu', 'Amponsah', 'Amoah', 'Darko',
    'Johansson', 'Andersen', 'Eriksson', 'Lindqvist', 'Bergstrom', 'Holmberg', 'Strand',
    'Müller', 'Fischer', 'Weber', 'Becker', 'Hoffmann', 'Schäfer', 'Koch', 'Richter',
    'Dubois', 'Lefevre', 'Moreau', 'Laurent', 'Simon', 'Michel', 'Leblanc', 'Fontaine',
    'Rossi', 'Ferrari', 'Esposito', 'Romano', 'Colombo', 'Ricci', 'Marino', 'Greco',
    'Santos', 'Ferreira', 'Oliveira', 'Costa', 'Rodrigues', 'Almeida', 'Nascimento',
    'Ivanov', 'Smirnov', 'Volkov', 'Popov', 'Sokolov', 'Lebedev', 'Kozlov', 'Novikov',
    'O\'Brien', 'O\'Connor', 'Murphy', 'Walsh', 'Byrne', 'Ryan', 'Doyle', 'Fitzgerald',
    'MacLeod', 'MacKenzie', 'MacDonald', 'Fraser', 'Cameron', 'Stewart', 'Robertson',
    'Beaumont', 'Whitfield', 'Thornton', 'Ashworth', 'Blackwood', 'Hartley', 'Pemberton',
    'Vandenberg', 'Hofstadter', 'Kowalski', 'Wojciechowski', 'Wiśniewski', 'Nowak',
    'Nakagawa', 'Hashimoto', 'Ogawa', 'Matsumoto', 'Inoue', 'Kimura', 'Hayashi',
    'Delgado', 'Vargas', 'Castillo', 'Jimenez', 'Romero', 'Alvarez', 'Ruiz', 'Herrera',
    # More English/American surnames
    'Abbott', 'Adkins', 'Aguilar', 'Allison', 'Alston', 'Andrade',
    'Anthony', 'Atkins', 'Avila', 'Ayala', 'Barber', 'Barker',
    'Barnett', 'Barr', 'Barrera', 'Barron', 'Bates', 'Bean',
    'Beck', 'Bender', 'Benjamin', 'Bentley', 'Benton',
    'Berg', 'Berger', 'Bernard', 'Bishop', 'Blair', 'Blanchard',
    'Blankenship', 'Blevins', 'Bolton', 'Booth', 'Bowman', 'Boyle',
    'Bradford', 'Brady', 'Brewer', 'Bridges', 'Bright',
    'Britt', 'Brock', 'Browning', 'Buckley', 'Bullock', 'Burgess',
    'Burke', 'Burks', 'Burnett', 'Burt', 'Bush', 'Byrd',
    'Cain', 'Caldwell', 'Callahan', 'Camacho', 'Cannon', 'Cantrell',
    'Cardenas', 'Carey', 'Carlson', 'Carr', 'Carroll', 'Casey',
    'Castaneda', 'Chambers', 'Chan', 'Chang', 'Chapman', 'Charles',
    'Chavez', 'Christensen', 'Christian', 'Church', 'Cisneros', 'Clayton',
    'Cline', 'Clements', 'Cochran', 'Coffey', 'Cohen',
    'Conner', 'Conrad', 'Conway', 'Cooke', 'Copeland', 'Corcoran',
    'Corley', 'Cortez', 'Cotton', 'Cowan', 'Coyle', 'Crosby',
    'Cross', 'Crowley', 'Cullen', 'Curry', 'Curtis', 'Daly',
    'Davidson', 'Dean', 'Decker', 'Delaney', 'Dennis', 'Dent',
    'Dickens', 'Dickerson', 'Dickinson', 'Dillon', 'Dorsey',
    'Dotson', 'Douglas', 'Drake', 'Dudley', 'Duncan', 'Dunlap',
    'Duran', 'Dyer', 'Eaton', 'English', 'Estrada',
    'Ewing', 'Farley', 'Farmer', 'Fields', 'Finley', 'Fleming',
    'Fletcher', 'Flowers', 'Flynn', 'Forbes', 'Foreman', 'Fowler',
    'Francis', 'Frank', 'Franks', 'Frazier', 'Frederick', 'Frost',
    'Fuentes', 'Fuller', 'Gaines', 'Gallagher', 'Gallegos', 'Garner',
    'Garza', 'Gates', 'Gibbs', 'Gilmore',
    'Glover', 'Golden', 'Goodman', 'Gore', 'Graves', 'Gregory',
    'Greer', 'Guerra', 'Gunn', 'Gutierrez', 'Hale', 'Hampton',
    'Hardy', 'Harper', 'Harrington', 'Hartman', 'Harvey', 'Hardin',
    'Hatch', 'Haynes', 'Head', 'Heath', 'Hendricks', 'Herman',
    'Herndon', 'Herring', 'Hester', 'Higgins', 'Hilton', 'Hobbs',
    'Hodge', 'Hodges', 'Holland', 'Holloway', 'Holman', 'Hooper',
    'Hopkins', 'Horn', 'Horton', 'Howell', 'Hubbard', 'Huffman',
    'Hull', 'Humphrey', 'Ingram', 'Jacobs', 'Jefferson', 'Jensen',
    'Johns', 'Johnston', 'Kelley', 'Keys', 'Kline',
    'Knapp', 'Knox', 'Lamb', 'Landry', 'Lang',
    'Larson', 'Lawson', 'Leblanc', 'Leonard', 'Levy', 'Lindsey',
    'Little', 'Livingston', 'Lloyd', 'Lowe', 'Lowery', 'Lucas',
    'Lugo', 'Lynch', 'Lynn', 'Lyons', 'Manning', 'Marks',
    'Marsh', 'Massey', 'Maxwell', 'Mcbride', 'Mccall', 'Mccarthy',
    'Mccormick', 'Mcfadden',
    'Mcguire', 'Mckee', 'Mcknight', 'Mclaughlin', 'Mcmillan', 'Mcneil',
    'Meadows', 'Mercer', 'Michaels', 'Middleton', 'Miranda', 'Molina',
    'Montgomery', 'Mooney', 'Morin', 'Morton', 'Mosley',
    'Mueller', 'Mullen', 'Malone', 'Moran', 'Munoz', 'Nash',
    'Navarro', 'Neal', 'Newman', 'Newton', 'Norman', 'Norris',
    'Norton', 'Nunez', 'Ochoa', 'Odom',
    'Oliver', 'Oneal', 'Orr', 'Osborn', 'Pacheco',
    'Padilla', 'Page', 'Parsons', 'Patton', 'Pena',
    'Pennington', 'Petersen', 'Petty', 'Pham', 'Pittman', 'Plummer',
    'Poole', 'Potts', 'Powers', 'Pratt', 'Preston', 'Prince',
    'Pruitt', 'Pugh', 'Ramsey', 'Randall', 'Randolph',
    'Reeves', 'Rios', 'Ripley', 'Roach', 'Robbins',
    'Robles', 'Rocha', 'Rodgers', 'Roman', 'Romero',
    'Salazar', 'Salinas', 'Sampson', 'Sanford', 'Saunders',
    'Savage', 'Sawyer', 'Sharp', 'Sheffield', 'Shelton',
    'Shields', 'Short', 'Simms', 'Singleton', 'Solis', 'Solomon',
    'Sosa', 'Stanley', 'Stark', 'Strickland', 'Strong', 'Stuart',
    'Suarez', 'Summers', 'Sutton', 'Swanson', 'Sweet',
    'Terry', 'Todd', 'Trevino', 'Trujillo',
    'Underwood', 'Valencia', 'Valenzuela', 'Vasquez', 'Vega', 'Velasquez',
    'Villanueva', 'Villarreal', 'Wade', 'Walton', 'Warner',
    'Watts', 'Weaver', 'Welch', 'Weston', 'Whitaker',
    'Whitehead', 'Wiley', 'Wilkins', 'Wilkinson',
    'Williamson', 'Winters', 'Wolf', 'Wolfe', 'Woodward',
    # More diverse international surnames
    'Abubakar', 'Achebe', 'Adeleke', 'Adeyinka', 'Aguilera', 'Ahmad',
    'Ahmed', 'Ajayi', 'Akinola', 'Akinwande', 'Aliyu', 'Alves',
    'Andrade', 'Araujo', 'Azevedo', 'Babatunde', 'Baig',
    'Barreto', 'Bassey', 'Batista', 'Bhattacharya', 'Bhatt', 'Bokhari',
    'Borges', 'Brito', 'Cabrera', 'Carvalho', 'Cavalcanti', 'Chaudhary',
    'Choudhury', 'Chowdhury', 'Cunha', 'Dasilva', 'Das', 'Dias',
    'Emeka', 'Fonseca', 'Gomes', 'Guerreiro', 'Hassan', 'Hayashi',
    'Hussain', 'Ibrahim', 'Islam', 'Jain', 'Kapoor', 'Kaur',
    'Khalil', 'Khan', 'Lopes', 'Machado', 'Madaki', 'Mahmood',
    'Maia', 'Mascarenhas', 'Matos', 'Mendes', 'Mohammed', 'Nair',
    'Nduka', 'Neto', 'Nunes', 'Nwosu', 'Obasi',
    'Ogundipe', 'Okeke', 'Okoro', 'Okunade', 'Olawale', 'Osei',
    'Oyewole', 'Pereira', 'Pires', 'Prakash', 'Qureshi', 'Rao',
    'Rauf', 'Reddy', 'Ribeiro', 'Rocha', 'Salgado', 'Sampaio',
    'Siddiqui', 'Siqueira', 'Soares', 'Sousa', 'Teixeira',
    'Usman', 'Venkataraman', 'Xavier', 'Yamada', 'Zafar', 'Zaidi',
    'Afolabi', 'Agboola', 'Akindele', 'Akomolafe', 'Alabi', 'Alade',
    'Amadi', 'Anozie', 'Asika', 'Awotunde', 'Ayoola', 'Badmus',
    'Balogun', 'Bankole', 'Dada', 'Dare', 'Dike', 'Duru',
    'Eboh', 'Edeh', 'Eze', 'Ezeobiora', 'Falade', 'Fashola',
    'Ibeh', 'Idemudia', 'Ihejirika', 'Ilo', 'Iroh', 'Isah',
    'Iyayi', 'Jegede', 'Jimoh', 'Kadiri', 'Lawal', 'Mba',
    'Mbah', 'Mbeki', 'Nkemdirim', 'Nwachukwu', 'Nwofor', 'Obi',
    'Obinna', 'Obodo', 'Odum', 'Ogbu', 'Ogundimu', 'Ogunleye',
    'Ojukwu', 'Oke', 'Okeke', 'Okonkwo', 'Okorie', 'Olayemi',
    'Olorunfemi', 'Oluwafemi', 'Omeje', 'Omoniyi', 'Onyeka', 'Orji',
    # Additional Asian surnames
    'Agarwal', 'Anand', 'Bose', 'Chakraborty', 'Chandra', 'Chatterjee',
    'Chaudhuri', 'Dasgupta', 'Datta', 'Dey', 'Dutta', 'Ghosh',
    'Hazra', 'Jana', 'Jha', 'Majumdar', 'Mandal', 'Mitra',
    'Mukherjee', 'Pal', 'Roy', 'Sarkar', 'Sengupta', 'Sinha',
    'Tagore', 'Tiwari', 'Tripathi', 'Verma', 'Yadav',
    'Anh', 'Dang', 'Dinh', 'Do', 'Hoang', 'Huynh',
    'Le', 'Ly', 'Ngo', 'Nguyen', 'Pham', 'Tran', 'Trinh', 'Vo',
    'Chung', 'Han', 'Hong', 'Hwang', 'Jang', 'Jeong', 'Jo',
    'Kang', 'Ko', 'Ku', 'Lee', 'Moon', 'Nam', 'Oh', 'Ryu',
    'Seo', 'Song', 'Yang', 'Yi', 'Yoo',
]

TITLES = [
    'Chief Executive Officer', 'Chief Financial Officer', 'Chief Operating Officer',
    'Chief Technology Officer', 'Chief Marketing Officer', 'Chief People Officer',
    'Chief Revenue Officer', 'Chief Legal Officer', 'Chief Compliance Officer',
    'Chief Strategy Officer', 'Chief Data Officer', 'Chief Risk Officer',
    'Chief Communications Officer', 'Chief Diversity Officer', 'Chief of Staff',
    'Vice President of Operations', 'Vice President of Sales', 'Vice President of Marketing',
    'Vice President of Business Development', 'Vice President of Finance',
    'Vice President of Human Resources', 'Vice President of Strategy',
    'Vice President of Corporate Affairs', 'Vice President of Stakeholder Engagement',
    'Vice President of Client Services', 'Vice President of Research',
    'Senior Director of Strategy', 'Senior Director of Corporate Affairs',
    'Senior Director of Stakeholder Engagement', 'Senior Director of Communications',
    'Senior Director of Finance', 'Senior Director of Human Resources',
    'Senior Director of Operations', 'Senior Director of Business Development',
    'Senior Director of Research & Analytics', 'Senior Director of Compliance',
    'Director of Public Relations', 'Director of Human Resources',
    'Director of Business Operations', 'Director of Client Success',
    'Director of Enterprise Partnerships', 'Director of Compliance',
    'Director of Corporate Development', 'Director of Financial Planning & Analysis',
    'Director of Talent Management', 'Director of Total Rewards',
    'Director of Compensation & Benefits', 'Director of Organizational Development',
    'Director of Government Relations', 'Director of Investor Relations',
    'Senior Manager of Corporate Initiatives', 'Senior Manager of Advocacy',
    'Senior Manager of Stakeholder Relations', 'Senior Manager of Operations',
    'Senior Manager of Compensation', 'Senior Manager of Benefits',
    'Senior Manager of Talent Acquisition', 'Senior Manager of Learning & Development',
    'Manager of Corporate Communications', 'Manager of Talent Acquisition',
    'Manager of Strategic Partnerships', 'Manager of Client Relations',
    'Manager of Compensation Programs', 'Manager of Benefits Administration',
    'Manager of Workforce Analytics', 'Manager of Corporate Governance',
    'Senior Analyst, Corporate Strategy', 'Senior Analyst, Market Intelligence',
    'Senior Analyst, Financial Planning', 'Senior Analyst, Compensation',
    'Senior Analyst, Workforce Planning', 'Senior Analyst, Organizational Effectiveness',
    'Business Development Associate', 'Corporate Affairs Specialist',
    'Communications Specialist', 'Operations Coordinator', 'Administrative Coordinator',
    'Executive Assistant to the CEO', 'Executive Assistant to the CFO',
    'Associate, Corporate Development', 'Associate, Public Affairs',
    'Associate, Compensation & Benefits', 'Associate, Talent Acquisition',
    'Research Associate', 'Policy Analyst', 'Governance Specialist',
    'Compensation Analyst', 'Benefits Analyst', 'HR Business Partner',
    # More C-suite variations
    'Chief Product Officer', 'Chief Customer Officer', 'Chief Innovation Officer',
    'Chief Transformation Officer', 'Chief Digital Officer', 'Chief Analytics Officer',
    'Chief Procurement Officer', 'Chief Supply Chain Officer', 'Chief Security Officer',
    'Chief Privacy Officer', 'Chief Sustainability Officer', 'Chief Impact Officer',
    'Chief Commercial Officer', 'Chief Growth Officer', 'Chief Advocacy Officer',
    # More VP-level titles
    'Vice President of Policy', 'Vice President of Government Affairs',
    'Vice President of External Affairs', 'Vice President of Institutional Partnerships',
    'Vice President of Program Management', 'Vice President of Product Management',
    'Vice President of Data & Analytics', 'Vice President of Technology',
    'Vice President of Diversity, Equity & Inclusion', 'Vice President of Sustainability',
    'Vice President of Risk Management', 'Vice President of Internal Audit',
    'Vice President of Supply Chain', 'Vice President of Procurement',
    'Vice President of Corporate Communications', 'Vice President of Brand',
    'Vice President of Customer Experience', 'Vice President of Innovation',
    'Vice President of Digital Transformation', 'Vice President of Mergers & Acquisitions',
    # More Director-level titles
    'Director of Policy Research', 'Director of External Communications',
    'Director of Advocacy & Outreach', 'Director of Program Operations',
    'Director of Data Science', 'Director of Product Strategy',
    'Director of ESG & Sustainability', 'Director of Social Impact',
    'Director of Grants Management', 'Director of Foundation Relations',
    'Director of Workforce Development', 'Director of Executive Education',
    'Director of Research Operations', 'Director of Knowledge Management',
    'Director of Digital Strategy', 'Director of Innovation Programs',
    'Director of Mergers & Acquisitions', 'Director of Corporate Strategy',
    'Director of Global Expansion', 'Director of International Partnerships',
    'Director of Legislative Affairs', 'Director of Regulatory Affairs',
    'Director of Ethics & Compliance', 'Director of Internal Investigations',
    'Director of Information Security', 'Director of Enterprise Risk',
    'Director of Treasury Operations', 'Director of Tax Planning',
    'Director of Accounting Operations', 'Director of Financial Reporting',
    'Director of Revenue Operations', 'Director of Sales Strategy',
    'Director of Channel Partnerships', 'Director of Customer Success',
    'Director of Brand Marketing', 'Director of Content Strategy',
    'Director of Digital Marketing', 'Director of Market Research',
    'Director of Product Development', 'Director of Technology Operations',
    'Director of Infrastructure', 'Director of Cloud Strategy',
    'Director of Enterprise Architecture', 'Director of Data Governance',
    # More Senior Manager titles
    'Senior Manager of Policy Analysis', 'Senior Manager of Program Delivery',
    'Senior Manager of Compliance Programs', 'Senior Manager of Data Analytics',
    'Senior Manager of Project Management', 'Senior Manager of Strategic Initiatives',
    'Senior Manager of External Relations', 'Senior Manager of Community Engagement',
    'Senior Manager of Regulatory Affairs', 'Senior Manager of Ethics Programs',
    'Senior Manager of Technology Risk', 'Senior Manager of Financial Analysis',
    'Senior Manager of Revenue Analytics', 'Senior Manager of Marketing Programs',
    'Senior Manager of Supply Chain', 'Senior Manager of Procurement Strategy',
    # More Manager titles
    'Manager of Policy Programs', 'Manager of Government Relations',
    'Manager of Data Engineering', 'Manager of Business Intelligence',
    'Manager of Project Delivery', 'Manager of Stakeholder Engagement',
    'Manager of Change Management', 'Manager of Communications Strategy',
    'Manager of Sustainability Programs', 'Manager of DEI Programs',
    'Manager of Regulatory Compliance', 'Manager of Ethics Programs',
    'Manager of Technology Projects', 'Manager of Digital Channels',
    'Manager of Revenue Enablement', 'Manager of Brand Strategy',
    'Manager of Total Rewards Programs', 'Manager of Learning Design',
    # Senior Analyst titles
    'Senior Analyst, Policy Research', 'Senior Analyst, Data Science',
    'Senior Analyst, Business Development', 'Senior Analyst, Corporate Communications',
    'Senior Analyst, ESG & Sustainability', 'Senior Analyst, Risk Management',
    'Senior Analyst, Operations', 'Senior Analyst, Government Relations',
    'Senior Analyst, Supply Chain', 'Senior Analyst, Treasury',
    # Individual contributor and specialist titles
    'Policy Research Specialist', 'Data Analytics Specialist', 'Compliance Specialist',
    'Program Coordinator', 'Project Coordinator', 'Communications Coordinator',
    'Technology Coordinator', 'Research Coordinator', 'Grants Coordinator',
    'Budget Analyst', 'Financial Analyst', 'Procurement Analyst',
    'Risk Analyst', 'Data Analyst', 'Marketing Analyst',
    'HR Analyst', 'Organizational Development Specialist', 'Training Specialist',
    'Learning & Development Coordinator', 'Talent Acquisition Specialist',
    'Total Rewards Specialist', 'Benefits Specialist', 'Payroll Specialist',
    'Executive Assistant to the COO', 'Executive Assistant to the CLO',
    'Executive Assistant to the CSO', 'Senior Administrative Assistant',
    'Office Manager', 'Facilities Manager', 'Project Manager',
    'Program Manager', 'Associate Program Manager', 'Technology Project Manager',
    'Associate, Strategy & Planning', 'Associate, Research & Analytics',
    'Associate, Policy & Government Relations', 'Associate, Communications',
    'Analyst, Financial Planning & Analysis', 'Analyst, Market Research',
    'Analyst, People Analytics', 'Analyst, Customer Insights',
    'Junior Associate', 'Staff Associate', 'Engagement Manager',
    'Portfolio Manager, Research', 'Relationship Manager', 'Account Executive',
    'Business Systems Analyst', 'Process Improvement Analyst',
    'Quality Assurance Specialist', 'Documentation Specialist',
    'Knowledge Management Specialist', 'Content Strategist', 'Grant Writer',
    'Speechwriter', 'Digital Content Manager', 'Social Media Manager',
    'Event Planner', 'Conference Coordinator', 'Volunteer Coordinator',
]

DEPARTMENTS = [
    'Executive Leadership', 'Finance & Accounting', 'Human Resources',
    'Corporate Strategy', 'Operations', 'Business Development',
    'Marketing & Communications', 'Legal & Compliance', 'Technology',
    'Client Services', 'Public Affairs', 'Administrative Services',
    'Stakeholder Relations', 'Corporate Development', 'Risk Management',
    'Research & Analytics', 'Investor Relations', 'Government Relations',
    'Total Rewards', 'Talent Management', 'Learning & Development',
    'Organizational Effectiveness', 'Workforce Planning', 'Corporate Governance',
    'Internal Audit', 'Data & Analytics', 'Knowledge Management',
    'Program Management', 'Policy & Advocacy', 'External Affairs',
    # More specific departments
    'Compensation & Benefits', 'Benefits Administration', 'Payroll Operations',
    'Talent Acquisition', 'Diversity, Equity & Inclusion', 'Employee Relations',
    'Labor Relations', 'Safety & Health', 'Environmental Health & Safety',
    'Facilities Management', 'Real Estate & Workplace Services', 'Procurement',
    'Supply Chain', 'Vendor Management', 'Information Technology',
    'Cybersecurity', 'Enterprise Architecture', 'Data Engineering',
    'Business Intelligence', 'Artificial Intelligence & Machine Learning',
    'Digital Transformation', 'Innovation Lab', 'Product Development',
    'Treasury', 'Tax', 'Financial Planning & Analysis',
    'Accounting', 'Reporting & Controls', 'Internal Controls',
    'M&A Integration', 'Strategic Finance', 'Regulatory Affairs',
    'Ethics & Compliance', 'Privacy & Data Protection',
    'Labor & Employment Law', 'Commercial Law', 'Litigation',
    'Intellectual Property', 'Contracts Management', 'Enterprise Risk',
    'Crisis Management', 'Business Continuity', 'Sustainability & ESG',
    'Social Impact', 'Philanthropy & Foundations', 'Community Affairs',
    'Legislative Affairs', 'Federal Affairs', 'State & Local Affairs',
    'Media Relations', 'Digital Communications', 'Brand Management',
    'Content & Creative', 'Events & Conferences', 'Member Services',
    'Customer Experience', 'Client Onboarding', 'Account Management',
    'Sales Operations', 'Revenue Operations', 'Pricing Strategy',
    'Market Development', 'Strategic Alliances', 'Ecosystem Partnerships',
    'Research Division', 'Survey Operations', 'Field Research',
    'Data Quality', 'Analytics Engineering', 'Decision Support',
    'Strategic Planning', 'Portfolio Management', 'PMO',
]


def generate_employee_batch(n=12):
    """Generate a batch of fake employee dicts."""
    employees = []
    # Use a time-based seed for uniqueness across visits, but pick reproducibly within the batch
    rng = random.Random()
    used_emails = set()

    for _ in range(n):
        first = rng.choice(FIRST_NAMES)
        last = rng.choice(LAST_NAMES)

        # Handle email collisions by appending a number
        base_email = f"{first.lower()}.{last.lower()}@acpwb.com"
        email = base_email
        counter = 2
        while email in used_emails:
            email = f"{first.lower()}.{last.lower()}{counter}@acpwb.com"
            counter += 1
        used_emails.add(email)

        seed = hashlib.md5(f"{first}{last}{rng.random()}".encode()).hexdigest()[:16]

        employees.append({
            'first_name': first,
            'last_name': last,
            'email': email,
            'title': rng.choice(TITLES),
            'department': rng.choice(DEPARTMENTS),
            'avatar_seed': seed,
        })

    return sorted(employees, key=lambda e: e['last_name'])
