# Generated by Django 5.2.15 on 2026-07-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficMinuteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.DateTimeField(db_index=True)),
                ('bot_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['minute', 'bot_type'], name='core_traffi_minute_1a1c87_idx')],
                'unique_together': {('minute', 'bot_type')},
            },
        ),
    ]
