# Generated by Django 5.2.12 on 2026-03-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('slug', models.CharField(max_length=512)),
                ('depth', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Archive Visit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.TextField()),
                ('referrer', models.TextField(blank=True)),
                ('trap_type', models.CharField(choices=[('archive', 'Archive Loop'), ('ghost_link', 'Ghost Link'), ('well_known', 'Well-Known File'), ('api', 'Fake API'), ('wiki', 'Wiki Page'), ('pow', 'PoW Challenge'), ('other', 'Other')], default='other', max_length=32)),
                ('query_string', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Crawler Visit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('body_paragraphs', models.JSONField(default=list)),
                ('watermark_token', models.CharField(max_length=16)),
                ('related_topics', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wiki Page',
                'ordering': ['topic'],
            },
        ),
    ]
