# Generated by Django 5.2.12 on 2026-03-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=64)),
                ('file_type', models.CharField(choices=[('csv', 'CSV Dataset'), ('pdf', 'PDF Document')], max_length=8)),
                ('pub_date', models.DateField()),
                ('summary', models.TextField()),
                ('watermark_token', models.CharField(max_length=16)),
                ('page_number', models.PositiveIntegerField(db_index=True, default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Public Report',
                'ordering': ['-pub_date', 'slug'],
            },
        ),
        migrations.AlterField(
            model_name='crawlervisit',
            name='trap_type',
            field=models.CharField(choices=[('archive', 'Archive Loop'), ('ghost_link', 'Ghost Link'), ('well_known', 'Well-Known File'), ('api', 'Fake API'), ('wiki', 'Wiki Page'), ('pow', 'PoW Challenge'), ('report_list', 'Report Listing'), ('report_download', 'Report Download'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
