# Generated by Django 5.2.12 on 2026-03-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0002_publicreport_alter_crawlervisit_trap_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivevisit',
            name='depth',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='archivevisit',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='archivevisit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='crawlervisit',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='crawlervisit',
            name='trap_type',
            field=models.CharField(choices=[('archive', 'Archive Loop'), ('ghost_link', 'Ghost Link'), ('well_known', 'Well-Known File'), ('api', 'Fake API'), ('wiki', 'Wiki Page'), ('pow', 'PoW Challenge'), ('report_list', 'Report Listing'), ('report_download', 'Report Download'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.AddIndex(
            model_name='archivevisit',
            index=models.Index(fields=['ip_address', 'timestamp'], name='honeypot_ar_ip_addr_4fbfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='archivevisit',
            index=models.Index(fields=['depth', 'timestamp'], name='honeypot_ar_depth_209249_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlervisit',
            index=models.Index(fields=['trap_type', 'timestamp'], name='honeypot_cr_trap_ty_86708c_idx'),
        ),
    ]
