# Generated by Django 5.2.12 on 2026-03-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0003_alter_archivevisit_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('next_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Internal Login Attempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='crawlervisit',
            name='trap_type',
            field=models.CharField(choices=[('archive', 'Archive Loop'), ('ghost_link', 'Ghost Link'), ('well_known', 'Well-Known File'), ('api', 'Fake API'), ('wiki', 'Wiki Page'), ('pow', 'PoW Challenge'), ('report_list', 'Report Listing'), ('report_download', 'Report Download'), ('dataset', 'Training Dataset'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
