# Generated by Django 5.2.12 on 2026-03-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0004_internalloginattempt_alter_crawlervisit_trap_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlervisit',
            name='bot_group',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='crawlervisit',
            name='bot_type',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='crawlervisit',
            index=models.Index(fields=['bot_type', 'timestamp'], name='honeypot_cr_bot_typ_b57eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlervisit',
            index=models.Index(fields=['bot_group', 'timestamp'], name='honeypot_cr_bot_gro_b831da_idx'),
        ),
    ]
