# Generated by Django 5.2.12 on 2026-03-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0005_crawlervisit_bot_group_crawlervisit_bot_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlervisit',
            name='host',
            field=models.CharField(blank=True, db_index=True, max_length=253),
        ),
    ]
