# Generated by Django 5.2.12 on 2026-03-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0006_add_host_to_crawlervisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlervisit',
            name='trap_type',
            field=models.CharField(choices=[('archive', 'Archive Loop'), ('ghost_link', 'Ghost Link'), ('well_known', 'Well-Known File'), ('api', 'Fake API'), ('wiki', 'Wiki Page'), ('pow', 'PoW Challenge'), ('report_list', 'Report Listing'), ('report_download', 'Report Download'), ('dataset', 'Training Dataset'), ('scanner_probe', 'Scanner Probe (404)'), ('env_probe', 'Config File Probe'), ('wp_probe', 'WordPress Probe'), ('webshell_probe', 'Webshell Probe'), ('canary_trigger', 'Canary Token Triggered'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.CreateModel(
            name='CanaryToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('token_type', models.CharField(choices=[('aws_keys', 'Canarytokens.org AWS Keys'), ('env_url', 'Self-hosted .env canary URL'), ('wp_config', 'wp-config.php canary URL'), ('git_config', '.git/config canary URL')], max_length=32)),
                ('canarytoken_token', models.CharField(blank=True, max_length=128)),
                ('aws_access_key_id', models.CharField(blank=True, max_length=32)),
                ('served_to_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('triggered', models.BooleanField(db_index=True, default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('triggered_ua', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canary Token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_type', 'served_at'], name='honeypot_ca_token_t_5a9743_idx'), models.Index(fields=['triggered', 'triggered_at'], name='honeypot_ca_trigger_fee6d9_idx')],
            },
        ),
    ]
