# Generated by Django 5.2.12 on 2026-03-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0007_alter_crawlervisit_trap_type_canarytoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canarytoken',
            name='aws_access_key_id',
        ),
        migrations.RemoveField(
            model_name='canarytoken',
            name='canarytoken_token',
        ),
        migrations.AlterField(
            model_name='canarytoken',
            name='token_type',
            field=models.CharField(choices=[('env_url', 'Self-hosted .env canary URL'), ('wp_config', 'wp-config.php canary URL'), ('git_config', '.git/config canary URL')], max_length=32),
        ),
    ]
