# Generated by Django 5.2.13 on 2026-04-11 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0008_remove_canarytoken_aws_access_key_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivevisit',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='crawlervisit',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
