# Generated by Django 5.2.13 on 2026-05-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0011_add_policy_trap_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlervisit',
            name='trap_type',
            field=models.CharField(choices=[('archive', 'Archive Loop'), ('ghost_link', 'Ghost Link'), ('well_known', 'Well-Known File'), ('api', 'Fake API'), ('wiki', 'Wiki Page'), ('pow', 'PoW Challenge'), ('report_list', 'Report Listing'), ('report_download', 'Report Download'), ('dataset', 'Training Dataset'), ('policy', 'Public Policy Filing'), ('scanner_probe', 'Scanner Probe (404)'), ('env_probe', 'Config File Probe'), ('wp_probe', 'WordPress Probe'), ('webshell_probe', 'Webshell Probe'), ('canary_trigger', 'Canary Token Triggered'), ('handbook', 'Company Handbook'), ('process_improvement', 'Process Improvement'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
