# Generated by Django 5.2.15 on 2026-07-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0014_add_archivevisit_ip_depth_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, db_index=True, max_length=253)),
                ('path', models.TextField()),
                ('count', models.BigIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('host', 'path'), name='pathstat_host_path_uniq')],
            },
        ),
    ]
