# Generated by Django 5.2.12 on 2026-09-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0015_pathstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('ip_version', models.PositiveSmallIntegerField(db_index=True, default=4)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=128)),
                ('region_name', models.CharField(blank=True, max_length=128)),
                ('city_name', models.CharField(blank=True, max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy_radius_km', models.PositiveIntegerField(blank=True, null=True)),
                ('asn', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('asn_org', models.CharField(blank=True, db_index=True, max_length=256)),
                ('is_hosting', models.BooleanField(db_index=True, default=False)),
                ('is_tor_exit', models.BooleanField(db_index=True, default=False)),
                ('lookup_ok', models.BooleanField(default=False)),
                ('enrichment_note', models.CharField(blank=True, max_length=255)),
                ('enriched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('geoip_db_date', models.DateField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('visit_count', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'IP Intelligence',
                'verbose_name_plural': 'IP Intelligence',
                'indexes': [models.Index(fields=['is_hosting', 'is_tor_exit'], name='honeypot_ip_is_host_d82d2c_idx'), models.Index(fields=['country_code', 'is_hosting'], name='honeypot_ip_country_be787e_idx')],
            },
        ),
    ]
