# Generated by Django 5.2.17 on 2026-09-15 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0018_daily_chunks_and_faster_compression'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedIPReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('classification', models.CharField(choices=[('human', 'Likely Human'), ('datacenter_bot', 'Datacenter Bot'), ('residential_proxy_bot', 'Residential Proxy Bot'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Published IP Reputation',
                'verbose_name_plural': 'Published IP Reputation',
            },
        ),
        migrations.CreateModel(
            name='IPReputationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('residential_proxy_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('classification', models.CharField(choices=[('human', 'Likely Human'), ('datacenter_bot', 'Datacenter Bot'), ('residential_proxy_bot', 'Residential Proxy Bot'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('evidence', models.JSONField(default=list)),
                ('score_version', models.CharField(default='v1', max_length=16)),
                ('first_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('last_scored_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'IP Reputation Score',
                'verbose_name_plural': 'IP Reputation Scores',
                'indexes': [models.Index(fields=['classification', 'residential_proxy_score'], name='honeypot_ip_classif_43c586_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('host', models.CharField(blank=True, max_length=253)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer_present', models.BooleanField(default=False)),
                ('first_seen_ip', models.BooleanField(db_index=True, default=False)),
                ('client_protocol', models.CharField(blank=True, max_length=16)),
                ('tls_protocol', models.CharField(blank=True, max_length=16)),
                ('tls_cipher', models.CharField(blank=True, max_length=64)),
                ('browser_headers_present', models.CharField(blank=True, max_length=512)),
                ('idempotency_key', models.UUIDField(blank=True, default=None, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Request Fingerprint',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='honeypot_re_ip_addr_9add29_idx')],
            },
        ),
    ]
