# Generated by Django 5.2.12 on 2026-03-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.EmailField(db_index=True, max_length=254)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.TextField(blank=True)),
                ('body_plain', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('mailgun_message_id', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'Inbound Email',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='HoneypotMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('match_confidence', models.CharField(choices=[('exact', 'Exact Email Match'), ('fuzzy', 'Fuzzy Name Match'), ('none', 'No Match')], default='none', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('generated_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_matches', to='people.generatedemployee')),
                ('original_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_matches', to='people.peoplepagevisit')),
                ('inbound_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='webhooks.inboundemail')),
            ],
            options={
                'verbose_name': 'Honeypot Match',
                'ordering': ['-matched_at'],
            },
        ),
    ]
