# Generated by Django 5.2.13 on 2026-04-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicemailRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('recording_sid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('recording_url', models.URLField(max_length=512)),
                ('recording_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('caller_number', models.CharField(blank=True, max_length=32)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('transcription_text', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Voicemail Recording',
                'verbose_name_plural': 'Voicemail Recordings',
                'ordering': ['-received_at'],
            },
        ),
    ]
