# Generated by Django 5.2.13 on 2026-04-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_voicemailrecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('caller_number', models.CharField(blank=True, max_length=32)),
                ('call_status', models.CharField(choices=[('completed', 'Completed'), ('busy', 'Busy'), ('no-answer', 'No Answer'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, max_length=16)),
                ('call_duration', models.IntegerField(default=0, help_text='Duration in seconds (0 for non-completed calls)')),
                ('raw_payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-received_at'],
            },
        ),
    ]
