# Generated by Django 5.2.12 on 2026-03-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fortune500Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('website', models.URLField()),
                ('industry', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Fortune 500 Company',
                'verbose_name_plural': 'Fortune 500 Companies',
                'ordering': ['rank'],
            },
        ),
    ]
