# Generated by Django 5.2.12 on 2026-03-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataOptOutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('request_type', models.CharField(choices=[('do_not_sell', 'Do Not Sell My Personal Information'), ('delete', 'Delete My Personal Information'), ('access', 'Access My Personal Information')], default='do_not_sell', max_length=32)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Data Opt-Out Request',
                'verbose_name_plural': 'Data Opt-Out Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
