# Generated by Django 5.2.13 on 2026-04-28 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_dataoptoutrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.PositiveIntegerField(db_index=True)),
                ('job_title', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_filename', models.CharField(blank=True, max_length=256)),
                ('resume_data', models.BinaryField(blank=True)),
                ('resume_content_type', models.CharField(blank=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='public.jobapplication')),
            ],
            options={
                'verbose_name': 'Job Application Document',
                'verbose_name_plural': 'Job Application Documents',
            },
        ),
    ]
