# Generated by Django 5.2.13 on 2026-05-08 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_jobapplication_jobapplicationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, default=2026)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('badge_name', models.CharField(max_length=100)),
                ('badge_title', models.CharField(blank=True, max_length=150)),
                ('badge_company', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('years_in_field', models.CharField(blank=True, max_length=20)),
                ('professional_membership', models.CharField(blank=True, max_length=200)),
                ('registration_type', models.CharField(choices=[('full', 'Full Conference'), ('day1', 'Day 1 Only'), ('day2', 'Day 2 Only')], default='full', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Conference Registration',
                'verbose_name_plural': 'Conference Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
