# Generated by Django 5.2.13 on 2026-05-08 01:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_conferenceregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceregistration',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
