# ── Meeting Minutes variant data ───────────────────────────────────────────────

_COMMITTEE_NAMES = [
    'Board of Directors',
    'Compensation Committee',
    'Audit and Risk Committee',
    'Human Resources Committee',
    'Executive Committee',
    'Finance and Investment Committee',
    'Nominating and Corporate Governance Committee',
    'Workforce Strategy Subcommittee',
    'Benefits Administration Committee',
    'Equal Employment Opportunity Committee',
    'Executive Compensation Subcommittee',
    'Regulatory Compliance Steering Committee',
    'Talent and Succession Committee',
    'Total Rewards Advisory Committee',
    'Cybersecurity Risk Subcommittee',
    'Enterprise Risk Management Committee',
    'Financial Risk Oversight Committee',
    'Public Policy Committee',
    'Shareholder Engagement Committee',
    'Environmental, Social, and Governance (ESG) Committee',
    'Sustainability and Corporate Responsibility Committee',
    'Retirement Plan Fiduciary Committee',
    '401(k) Investment Committee',
    'Health and Welfare Benefits Committee',
    'Pay Equity Task Force',
    'Leadership Development Committee',
    'Diversity, Equity, and Inclusion (DEI) Council',
    'Capital Allocation Committee',
    'M&A Steering Committee',
    'Treasury Committee',
    'Special Committee for Strategic Alternatives',
    'Independent Investigation Committee',
    'CEO Search Committee',
    'Operations Committee',
    'Technology and Innovation Committee',
    'Strategy Committee',
    'Disclosure Committee',
    'Ethics and Compliance Committee',
    'Crisis Management Committee',
    'Data Governance Council',
    'Workplace Safety Committee',
    'Real Estate and Facilities Committee',
    'Ad Hoc Committee on AI Governance',
    'Joint Labor-Management Committee',
    'Pension Investment Subcommittee',
    'Healthcare Cost Containment Task Force',
    'Global Compensation Subcommittee',
    'Executive Session of the Board',
    'Independent Directors Committee',
    'Advisory Panel on Workforce Analytics',
    'Steering Committee for Project Phoenix',
    'Compensation Philosophy Review Task Force',
    'HR Technology Steering Committee',
    'Employee Stock Plan Administration Committee',
    'Non-Qualified Deferred Compensation Plan Committee',
    'Severance Plan Oversight Committee',
    'Relocation Policy Committee',
    'Internal Controls Committee',
    'Business Continuity Planning Committee',
    'Government Affairs Committee',
    'Charitable Contributions Committee',
    'Political Action Committee (PAC) Board',
    'Intellectual Property Committee',
    'Supply Chain Risk Committee',
    'Customer Advisory Board',
    'Product Strategy Committee',
    'Digital Transformation Oversight Committee',
    'Regional Leadership Council - Americas',
    'Regional Leadership Council - EMEA',
    'Regional Leadership Council - APAC',
    'Joint Venture Oversight Committee',
    'Special Litigation Committee',
    'Executive Talent Review Committee',
    'Workforce Restructuring Committee',
    'Benefits Design Subcommittee',
    'Incentive Compensation Governance Committee',
    'Sales Compensation Committee',
    'R&D Investment Committee',
    'Corporate Security Committee',
    'Insider Trading Compliance Committee',
    'Records Management Committee',
    'Brand and Reputation Committee',
    'Advisory Board',
    'Technical Advisory Board',
    'Scientific Advisory Board',
    'Customer Experience Council',
    'Product Council',
    'Pricing Committee',
    'Marketing and Brand Committee',
    'Sales Leadership Council',
    'Channel Partner Advisory Board',
    'Supply Chain Council',
    'Logistics and Fulfillment Committee',
    'Procurement Committee',
    'Manufacturing Oversight Committee',
    'Quality and Safety Committee',
    'Environmental Health and Safety (EHS) Committee',
    'Real Estate Committee',
    'Facilities and Capital Projects Committee',
    'IT Steering Committee',
    'Information Security Council',
    'Data Privacy Committee',
    'Architecture Review Board',
    'Digital Strategy Committee',
    'Innovation Council',
    'Research and Development Committee',
    'Intellectual Property Strategy Committee',
    'Legal and Regulatory Affairs Committee',
    'Litigation Oversight Committee',
    'Government Relations Committee',
    'Public Affairs Committee',
    'Corporate Social Responsibility (CSR) Committee',
    'Foundation Board',
    'Political Action Committee (PAC) Steering Committee',
    'Employee Benefits Fiduciary Committee',
    'Retirement Savings Plan Committee',
    'Health Plan Governance Committee',
    'Executive Compensation and Talent Committee',
    'Talent Management and Succession Planning Committee',
    'DEI Executive Council',
    'Employee Relations Committee',
    'Workforce Planning Committee',
    'HR Policy Committee',
    'Global Mobility Committee',
    'Sales Compensation Governance Committee',
    'Incentive Plan Review Committee',
    'Equity Awards Committee',
    'Deferred Compensation Plan Committee',
    'Executive Leadership Team (ELT)',
    'Senior Leadership Team (SLT)',
    'Management Committee',
    'Operating Committee',
    'Investment Committee',
    'Capital Review Board',
    'Treasury and Finance Committee',
    'Risk Management Committee',
    'Internal Audit Committee',
    'Disclosure and Controls Committee',
    'Ethics Committee',
    'Compliance Oversight Committee',
    'Business Continuity Steering Committee',
    'Crisis Response Team',
    'M&A Integration Steering Committee',
    'Divestiture Committee',
    'Joint Venture Management Committee',
    'Strategic Partnerships Committee',
    'Regional Executive Committee - North America',
    'Regional Executive Committee - Europe',
    'Regional Executive Committee - Asia-Pacific',
    'Regional Executive Committee - Latin America',
    'Country Leadership Team - UK',
    'Country Leadership Team - Germany',
    'Country Leadership Team - China',
    'Country Leadership Team - Brazil',
    'Special Committee of the Board',
    'Independent Directors Session',
    'Executive Session (Non-management directors)',
    'Ad Hoc Committee on Shareholder Proposals',
    'Ad Hoc Committee on CEO Search',
    'Ad Hoc Committee on Strategic Review',
    'Technology Subcommittee of the Board',
    'Cybersecurity Committee of the Board',
    'ESG Steering Committee',
    'Sustainability Council',
    'Human Rights Committee',
    'Product Safety and Quality Committee',
    'Customer Advisory Council',
    'Supplier Diversity Council',
    'Workplace Modernization Task Force',
    'Future of Work Committee',
    'AI Ethics Council',
    'Data Analytics Governance Board',
    'Digital Transformation Executive Committee',
    'Innovation Board',
    'Corporate Venture Capital Investment Committee',
    'Brand Council',
    'Reputation Risk Committee',
    'Global Security Committee',
    'Pension Trust Investment Committee',
    '401(k) Administrative Committee',
    'Health and Wellness Committee',
    'Executive Bonus Plan Committee',
    'Long-Term Incentive Plan Committee',
    'Stock Plan Administration Committee',
    'Compensation Philosophy Task Force',
    'Talent Review and Calibration Committee',
    'Leadership Pipeline Committee',
    'High-Potential Talent Committee',
    'Employee Engagement Council',
    'Labor-Management Partnership Committee',
    'Grievance Review Committee',
    'Safety Review Board',
    'Environmental Compliance Committee',
    'Capital Projects Review Committee',
    'IT Governance Committee',
    'Data Classification Committee',
    'Privacy Incident Response Team',
    'Enterprise Architecture Committee',
    'R&D Portfolio Committee',
    'Patent Review Committee',
    'Trademark Committee',
    'Litigation Strategy Committee',
    'Regulatory Response Committee',
    'Government Contracts Compliance Committee',
    'CSR Reporting Committee',
    'Foundation Grant Committee',
    'PAC Contributions Committee',
    'Treasury Risk Committee',
    'Counterparty Risk Committee',
    'Credit Committee',
    'Market Risk Committee',
    'Operational Risk Committee',
    'Model Risk Governance Committee',
    'SOX Steering Committee',
    'Financial Reporting Committee',
    'SEC Disclosure Committee',
    'Business Resilience Committee',
    'Pandemic Response Team',
    'Integration Management Office (IMO) Steering Committee',
    'Carve-Out Committee',
    'Alliance Management Committee',
    'Regional Sales Council - Americas',
    'Regional Sales Council - EMEA',
    'Regional Sales Council - APAC',
    'Global Product Council',
    'Global Marketing Council',
    'Global Operations Council',
    'Global HR Leadership Team',
    'Global Finance Leadership Team',
    'Global Legal Leadership Team',
    'Executive Offsite Planning Committee',
    'Annual Meeting Planning Committee',
    'Investor Day Steering Committee',
    'Shareholder Outreach Committee',
    'Proxy Statement Review Committee',
    'Director Education Committee',
    'Board Refreshment Committee',
    'CEO Performance Review Committee',
    'Executive Talent and Organization Committee',
    'Culture and Engagement Committee',
    'Workforce Health and Safety Committee',
    'Digital Ethics Committee',
    'Algorithmic Fairness Committee',
    'Responsible AI Committee',
    'Data Monetization Committee',
    'Platform Governance Committee',
    'Ecosystem Strategy Committee',
    'Open Source Program Office (OSPO) Steering Committee',
    'Corporate Development Committee',
    'Strategic Investment Committee',
    'Venture Arm Investment Committee',
    'Pricing and Monetization Committee',
    'Go-to-Market Committee',
    'Customer Success Leadership Council',
    'Partner Ecosystem Committee',
    'Global Supply Chain Committee',
    'Logistics and Trade Compliance Committee',
    'Strategic Sourcing Committee',
    'Manufacturing Excellence Committee',
    'Quality Management Review Board',
    'Plant Safety Committee',
    'Fleet Management Committee',
    'Physical Security Committee',
    'IT Infrastructure Committee',
    'Cloud Center of Excellence',
    'Cyber Defense Committee',
    'Insider Threat Committee',
    'Privacy by Design Council',
    'Records and Information Management Committee',
    'IP Licensing Committee',
    'Government Pricing Committee',
    'Trade Compliance Committee',
    'Anti-Corruption Committee',
    'Sanctions Compliance Committee',
    'AML Oversight Committee',
    'Fraud Risk Management Committee',
    'Whistleblower Review Committee',
    'Corporate Investigations Committee',
    'Business Ethics Council',
    'Climate Action Steering Committee',
    'Water Stewardship Committee',
    'Human Rights Working Group',
    'Sustainable Supply Chain Committee',
    'Community Investment Committee',
    'Employee Volunteer Council',
    'Foundation Investment Committee',
    'PAC Governance Committee',
    'Defined Benefit Plan Committee',
    'Defined Contribution Plan Committee',
    'Welfare Benefits Plan Committee',
    'Executive Severance Committee',
    'Change in Control Committee',
    'Equity Compensation Subcommittee',
    'Global Stock Plans Committee',
    'Executive Relocation Committee',
    'Talent Acquisition Council',
    'University Relations Committee',
    'Leadership Development and Coaching Committee',
    'Performance Management Committee',
    'Employee Recognition Committee',
    'Workforce Restructuring Oversight Committee',
    'Joint Health and Safety Committee',
    'Ergonomics Committee',
    'Process Safety Management Committee',
    'Capital Investment Review Committee',
    'Real Estate Strategy Committee',
    'IT Project Portfolio Committee',
    'Technology Standards Committee',
    'Cyber Incident Response Team',
    'Data Loss Prevention Committee',
    'Identity and Access Management Committee',
    'R&D Governance Committee',
    'New Product Introduction Committee',
    'IP Litigation Committee',
    'Contract Review Committee',
    'Regulatory Filings Committee',
    'Lobbying Compliance Committee',
    'Corporate Philanthropy Committee',
    'Foundation Audit Committee',
    'PAC Compliance Committee',
    'Foreign Exchange Committee',
    'Commodity Risk Committee',
    'Interest Rate Risk Committee',
    'Liquidity Risk Committee',
    'Credit Risk Management Committee',
    'Financial Model Validation Committee',
    'SOX Compliance Subcommittee',
    'External Reporting Committee',
    'SEC Comment Letter Response Committee',
    'Disaster Recovery Steering Committee',
    'Geopolitical Risk Committee',
    'Separation Management Office (SMO) Steering Committee',
    'Post-Merger Integration Leadership Team',
    'Strategic Alliance Review Board',
    'China Leadership Team',
    'India Leadership Team',
    'Japan Leadership Team',
    'UK and Ireland Leadership Team',
    'DACH Region Leadership Team',
    'Nordics Leadership Team',
    'ASEAN Leadership Team',
    'Board Strategy Offsite Planning Committee',
    'Annual Operating Plan Review Committee',
    'Long-Range Strategic Plan Committee',
    'Director Nominating Committee',
    'Board Succession Planning Committee',
    'Lead Independent Director Meeting',
    'Executive Committee of the Board',
    'Special Committee on M&A',
    'Ad Hoc Pricing Committee',
    'Go-to-Market Strategy Council',
    'Customer Retention Committee',
    'Partner Program Committee',
    'Global Logistics Council',
    'Sourcing and Procurement Council',
    'Manufacturing Leadership Team',
    'Quality Council',
    'Global EHS Council',
    'Corporate Real Estate Council',
    'IT Executive Steering Committee',
    'Global Information Security Council',
    'Privacy Leadership Council',
    'Enterprise Data Council',
    'Digital Innovation Council',
    'R&D Leadership Team',
    'Global Legal and Compliance Council',
    'Global Government Affairs Council',
    'Corporate Responsibility Council',
    'Global Benefits Governance Committee',
    'Global Talent Management Council',
    'Global DEI Council',
    'Global Employee Relations Council',
    'Global HR Operations Council',
    'Global Finance Council',
    'Global Treasury Council',
    'Global Tax Council',
    'Global Internal Audit Council',
    'Global Risk Council',
    'Global M&A Council',
    'Global Strategy Council',
    'Americas Leadership Council',
    'EMEA Leadership Council',
    'APAC Leadership Council',
    'Latin America Leadership Council',
    'Greater China Leadership Council',
]

_MEETING_LOCATIONS = [
    'Milwaukee, WI \u2014 Registered Office, Suite 1400',
    'Conference Room 4B, Milwaukee Headquarters',
    'Remote / Videoconference (Meeting ID on record)',
    'Chicago Satellite Office, 200 W. Monroe St.',
    'Schaumburg Regional Office \u2014 Board Room',
    'Madison, WI \u2014 State Street Campus, Room 221',
    'Detroit Regional Hub \u2014 Conference Center A',
    'Minneapolis Field Office \u2014 Executive Suite',
    'Indianapolis Regional Center \u2014 Boardroom',
    'Cincinnati Client Services Office \u2014 Room B',
    'New York, NY \u2014 5th Avenue Conference Center',
    'San Francisco, CA \u2014 Embarcadero Center West Tower',
    'Boston, MA \u2014 Seaport District Office, Room 12A',
    'Atlanta, GA \u2014 Midtown Regional Hub',
    'Dallas, TX \u2014 Uptown Office, Boardroom 3',
    'Denver, CO \u2014 LoDo Office, Conference Room Aspen',
    'Seattle, WA \u2014 South Lake Union Campus, Building 4',
    'Washington, D.C. \u2014 K Street Policy Office',
    'Nashville, TN \u2014 Music Row Satellite Office',
    'Phoenix, AZ \u2014 Camelback Corridor Office',
    'Austin, TX \u2014 Domain Innovation Center',
    'Philadelphia, PA \u2014 Center City Office, Liberty Suite',
    'Charlotte, NC \u2014 SouthPark Corporate Center',
    'Miami, FL \u2014 Brickell Financial District Office',
    'Houston, TX \u2014 Energy Corridor Campus',
    'Salt Lake City, UT \u2014 Silicon Slopes Office',
    'The Whitmore Room, Milwaukee Headquarters',
    'Ashworth Conference Center, Chicago Office',
    'Holloway Auditorium, Virtual Town Hall',
    'Pemberton Innovation Hub, San Francisco Office',
    'Langford Collaboration Space, Remote/Virtual',
    'East Coast Regional Office, Boardroom',
    'West Coast Hub, Executive Briefing Center',
    'Southern Division HQ, Conference Room Alpha',
    'Central Region Operations Center, Room 301',
    'ACPWB Secure Portal (Meeting ID: {n})',
    'Offsite: The Peninsula Chicago, Boardroom',
    'Offsite: Four Seasons Austin, Conference Suite',
    'Offsite: The Breakers Palm Beach, Gold Room',
    'Offsite: Skadden, Arps, Slate, Meagher & Flom LLP Offices, NYC',
    'Offsite: Latham & Watkins LLP Offices, Chicago',
    'Palo Alto, CA \u2014 Sand Hill Road Office',
    'Stamford, CT \u2014 Harbor Point Office',
    'Greenwich, CT \u2014 Executive Offices',
    'Boca Raton, FL \u2014 Mizner Park Office',
    'La Jolla, CA \u2014 Prospect Street Office',
    'McLean, VA \u2014 Tysons Corner Office',
    'Plano, TX \u2014 Legacy West Campus',
    'Bellevue, WA \u2014 Downtown Office',
    'Cambridge, MA \u2014 Kendall Square Office',
    'Irvine, CA \u2014 Spectrum Center Office',
    'Tampa, FL \u2014 Water Street Office',
    'San Diego, CA \u2014 UTC Office',
    'Raleigh, NC \u2014 Research Triangle Park Campus',
    'Kansas City, MO \u2014 Plaza Office',
    'St. Louis, MO \u2014 Clayton Office',
    'Cleveland, OH \u2014 Key Tower Office',
    'Pittsburgh, PA \u2014 PPG Place Office',
    'London, UK \u2014 Canary Wharf Office',
    'Toronto, ON \u2014 Bay Street Office',
    'Frankfurt, DE \u2014 TaunusTurm Office',
    'Singapore \u2014 Marina Bay Financial Centre',
    'Hong Kong \u2014 International Commerce Centre',
    'Tokyo, JP \u2014 Marunouchi Building',
    'Virtual Meeting (Zoom)',
    'Virtual Meeting (Microsoft Teams)',
    'Virtual Meeting (Webex)',
    'Virtual Meeting (Google Meet)',
    'Teleconference (Dial-in details circulated)',
    'Offsite: The Ritz-Carlton, Naples, FL',
    'Offsite: The Broadmoor, Colorado Springs, CO',
    'Offsite: Montage Laguna Beach, CA',
    'Offsite: The Greenbrier, White Sulphur Springs, WV',
    'Offsite: Pebble Beach Resorts, CA',
    'Offsite: The Sanctuary at Kiawah Island, SC',
    'Offsite: Amangani, Jackson, WY',
    'Offsite: Blackberry Farm, Walland, TN',
    'Offsite: Twin Farms, Barnard, VT',
    'Offsite: Post Ranch Inn, Big Sur, CA',
    'Offsite: The Little Nell, Aspen, CO',
    'Offsite: The Cloister at Sea Island, GA',
    'Offsite: The Lodge at Blue Sky, Wanship, UT',
    'Offsite: The Mayflower Inn & Spa, Washington, CT',
    'Offsite: The Inn at Little Washington, Washington, VA',
    'Offsite: Auberge du Soleil, Rutherford, CA',
    'Offsite: Calistoga Ranch, Calistoga, CA',
    'Offsite: Meadowood Napa Valley, St. Helena, CA',
    'Offsite: SingleThread Farms, Healdsburg, CA',
    'Offsite: The French Laundry, Yountville, CA',
    'Offsite: Per Se, New York, NY',
    'Offsite: Alinea, Chicago, IL',
    'Offsite: Eleven Madison Park, New York, NY',
    'Offsite: Le Bernardin, New York, NY',
    'Offsite: Daniel, New York, NY',
    'Offsite: Jean-Georges, New York, NY',
    'Offsite: The Modern, New York, NY',
    'Offsite: Gramercy Tavern, New York, NY',
    'Offsite: Blue Hill at Stone Barns, Tarrytown, NY',
    'Offsite: The Inn at Perry Cabin, St. Michaels, MD',
    'Offsite: The Jefferson, Washington, D.C.',
    'Offsite: The Hay-Adams, Washington, D.C.',
    'Offsite: The St. Regis, Washington, D.C.',
    'Offsite: The Willard InterContinental, Washington, D.C.',
    'Offsite: The Watergate Hotel, Washington, D.C.',
    'Offsite: The Line Hotel, Washington, D.C.',
    'Offsite: The Dupont Circle Hotel, Washington, D.C.',
    'Offsite: The Rosewood, Washington, D.C.',
    'Offsite: The Four Seasons, Washington, D.C.',
    'Offsite: The Park Hyatt, Washington, D.C.',
    'Offsite: The Conrad, Washington, D.C.',
    'Offsite: The Waldorf Astoria, Washington, D.C.',
    'Offsite: The Ritz-Carlton, Georgetown, Washington, D.C.',
    'Offsite: The Ritz-Carlton, Tysons Corner, VA',
    'Offsite: The Salamander Resort & Spa, Middleburg, VA',
    'Offsite: The Inn at Willow Grove, Orange, VA',
    'Offsite: The Clifton, Charlottesville, VA',
    'Offsite: Keswick Hall, Keswick, VA',
    'Offsite: The Omni Homestead Resort, Hot Springs, VA',
    'Offsite: Primland, Meadows of Dan, VA',
    'Offsite: The Greenbrier, White Sulphur Springs, WV',
    'Offsite: The Hotel Hershey, Hershey, PA',
    'Offsite: Nemacolin, Farmington, PA',
    'Offsite: The Rittenhouse, Philadelphia, PA',
    'Offsite: The Four Seasons, Philadelphia, PA',
    'Offsite: The Logan, Philadelphia, PA',
    'Offsite: The Bellevue Hotel, Philadelphia, PA',
    'Offsite: The Pierre, New York, NY',
    'Offsite: The St. Regis, New York, NY',
    'Offsite: The Plaza, New York, NY',
    'Offsite: The Carlyle, A Rosewood Hotel, New York, NY',
    'Offsite: The Mark, New York, NY',
    'Offsite: The Lowell, New York, NY',
    'Offsite: The Greenwich Hotel, New York, NY',
    'Offsite: The Crosby Street Hotel, New York, NY',
    'Offsite: The Whitby Hotel, New York, NY',
    'Offsite: The Baccarat Hotel, New York, NY',
    'Offsite: The Mandarin Oriental, New York, NY',
    'Offsite: The Park Hyatt, New York, NY',
    'Offsite: The Ritz-Carlton Central Park, New York, NY',
    'Offsite: The Four Seasons Downtown, New York, NY',
    'Offsite: The Langham, Chicago, IL',
    'Offsite: The Peninsula, Chicago, IL',
    'Offsite: The Waldorf Astoria, Chicago, IL',
    'Offsite: The Park Hyatt, Chicago, IL',
    'Offsite: The Ritz-Carlton, Chicago, IL',
    'Offsite: The Four Seasons, Chicago, IL',
    'Offsite: The Thompson, Chicago, IL',
    'Offsite: The Hoxton, Chicago, IL',
    'Offsite: The Soho House, Chicago, IL',
    'Offsite: The Viceroy, Chicago, IL',
    'Offsite: The Gwen, a Luxury Collection Hotel, Chicago, IL',
    'Offsite: The LondonHouse, Chicago, IL',
    'Offsite: The Blackstone, Autograph Collection, Chicago, IL',
    'Offsite: The Drake, a Hilton Hotel, Chicago, IL',
    'Offsite: The Palmer House, a Hilton Hotel, Chicago, IL',
    'Offsite: The Art Institute of Chicago, Chicago, IL',
    'Offsite: The Field Museum, Chicago, IL',
    'Offsite: The Museum of Science and Industry, Chicago, IL',
    'Offsite: The Adler Planetarium, Chicago, IL',
    'Offsite: The Shedd Aquarium, Chicago, IL',
    'Offsite: The Lyric Opera of Chicago, Chicago, IL',
    'Offsite: The Chicago Symphony Orchestra, Chicago, IL',
    'Offsite: The Steppenwolf Theatre, Chicago, IL',
    'Offsite: The Goodman Theatre, Chicago, IL',
    'Offsite: The Second City, Chicago, IL',
    'Offsite: The University of Chicago, Chicago, IL',
    'Offsite: Northwestern University, Evanston, IL',
    'Offsite: The Union League Club of Chicago, Chicago, IL',
    'Offsite: The Metropolitan Club, Chicago, IL',
    'Offsite: The Chicago Club, Chicago, IL',
    'Offsite: The Standard Club, Chicago, IL',
    'Offsite: The Mid-America Club, Chicago, IL',
    'Offsite: The Casino, Chicago, IL',
    'Offsite: The Saddle & Cycle Club, Chicago, IL',
    'Offsite: The Shoreacres, Lake Bluff, IL',
    'Offsite: The Old Elm Club, Highland Park, IL',
    'Offsite: The Chicago Golf Club, Wheaton, IL',
    'Offsite: The Medinah Country Club, Medinah, IL',
    'Offsite: The Butler National Golf Club, Oak Brook, IL',
    'Offsite: The Olympia Fields Country Club, Olympia Fields, IL',
    'Offsite: The Rich Harvest Farms, Sugar Grove, IL',
    'Offsite: The Merit Club, Libertyville, IL',
    'Offsite: The Conway Farms Golf Club, Lake Forest, IL',
    'Offsite: The Glen Club, Glenview, IL',
    'Offsite: The Kemper Lakes Golf Club, Kildeer, IL',
    'Offsite: The Cog Hill Golf & Country Club, Lemont, IL',
    'Offsite: The Dubsdread at Cog Hill, Lemont, IL',
    'Offsite: The Beverly Country Club, Chicago, IL',
    'Offsite: The Skokie Country Club, Glencoe, IL',
    'Offsite: The Indian Hill Club, Winnetka, IL',
    'Offsite: The Onwentsia Club, Lake Forest, IL',
    'Offsite: The Knollwood Club, Lake Forest, IL',
    'Offsite: The Exmoor Country Club, Highland Park, IL',
    'Offsite: The Northmoor Country Club, Highland Park, IL',
    'Offsite: The Sunset Ridge Country Club, Northfield, IL',
    'Offsite: The Westmoreland Country Club, Wilmette, IL',
    'Offsite: The Evanston Golf Club, Skokie, IL',
    'Offsite: The Park Ridge Country Club, Park Ridge, IL',
    'Offsite: The Oak Park Country Club, River Grove, IL',
    'Offsite: The Riverside Golf Club, Riverside, IL',
    'Offsite: The La Grange Country Club, La Grange, IL',
    'Offsite: The Hinsdale Golf Club, Clarendon Hills, IL',
    'Offsite: The Butterfield Country Club, Oak Brook, IL',
    'Offsite: The Oak Brook Hills Resort, Oak Brook, IL',
    'Offsite: The Drake Oak Brook, Autograph Collection, Oak Brook, IL',
    'Offsite: The Hyatt Lodge Oak Brook, Oak Brook, IL',
    'Offsite: The Renaissance Schaumburg Convention Center Hotel, Schaumburg, IL',
    'Offsite: The Eaglewood Resort & Spa, Itasca, IL',
    'Offsite: The Lincolnshire Marriott Resort, Lincolnshire, IL',
    'Offsite: The Grand Geneva Resort & Spa, Lake Geneva, WI',
    'Offsite: The American Club, Kohler, WI',
    'Offsite: The Pfister Hotel, Milwaukee, WI',
    'Offsite: The Saint Kate - The Arts Hotel, Milwaukee, WI',
    'Offsite: The Kimpton Journeyman Hotel, Milwaukee, WI',
    'Offsite: The Iron Horse Hotel, Milwaukee, WI',
    'Offsite: The Edgewater, Madison, WI',
    'Offsite: The Graduate Madison, Madison, WI',
    'Offsite: The Fluno Center, Madison, WI',
    'Offsite: The Monona Terrace, Madison, WI',
    'Offsite: The Wisconsin Institutes for Discovery, Madison, WI',
    'Offsite: The Pyle Center, Madison, WI',
    'Offsite: The Memorial Union, Madison, WI',
    'Offsite: The Union South, Madison, WI',
    'Offsite: The Overture Center for the Arts, Madison, WI',
    'Offsite: The Madison Club, Madison, WI',
    'Offsite: The University Club, Madison, WI',
    'Offsite: The Nakoma Golf Club, Madison, WI',
    'Offsite: The Blackhawk Country Club, Madison, WI',
    'Offsite: The Maple Bluff Country Club, Madison, WI',
    'Offsite: The Bishops Bay Country Club, Middleton, WI',
    'Offsite: The TPC Wisconsin, Madison, WI',
    'Offsite: The Erin Hills Golf Course, Erin, WI',
    'Offsite: The Whistling Straits, Sheboygan, WI',
    'Offsite: The Blackwolf Run, Kohler, WI',
    'Offsite: The Sand Valley Golf Resort, Nekoosa, WI',
    'Offsite: The SentryWorld, Stevens Point, WI',
    'Offsite: The Milwaukee Country Club, River Hills, WI',
    'Offsite: The Blue Mound Golf & Country Club, Wauwatosa, WI',
    'Offsite: The Chenequa Country Club, Hartland, WI',
    'Offsite: The Oconomowoc Lake Club, Oconomowoc, WI',
    'Offsite: The Pine Hills Country Club, Sheboygan, WI',
    'Offsite: The Oneida Golf and Country Club, Green Bay, WI',
    'Offsite: The Green Bay Country Club, Green Bay, WI',
    'Offsite: The Butte des Morts Country Club, Appleton, WI',
    'Offsite: The North Shore Country Club, Mequon, WI',
    'Offsite: The West Bend Country Club, West Bend, WI',
    'Offsite: The Racine Country Club, Racine, WI',
    'Offsite: The Kenosha Country Club, Kenosha, WI',
    'Offsite: The Janesville Country Club, Janesville, WI',
    'Offsite: The Beloit Club, Beloit, WI',
    'Offsite: The Eau Claire Golf & Country Club, Altoona, WI',
    'Offsite: The Wausau Country Club, Schofield, WI',
    'Offsite: The La Crosse Country Club, Onalaska, WI',
    'Offsite: The Oshkosh Country Club, Oshkosh, WI',
    'Offsite: The Ridgeway Country Club, Neenah, WI',
    'Offsite: The Stevens Point Country Club, Stevens Point, WI',
    'Offsite: The Minocqua Country Club, Minocqua, WI',
    'Offsite: The Trout Lake Golf Club, Arbor Vitae, WI',
    'Offsite: The Plum Lake Golf Club, Sayner, WI',
    'Offsite: The St. Germain Golf Club, St. Germain, WI',
    'Offsite: The Eagle River Golf Course, Eagle River, WI',
    'Offsite: The Timber Ridge Golf Club, Minocqua, WI',
    'Offsite: The Wild Rock Golf Club, Wisconsin Dells, WI',
    'Offsite: The Trappers Turn Golf Club, Wisconsin Dells, WI',
    'Offsite: The Kalahari Resort, Wisconsin Dells, WI',
    'Offsite: The Wilderness Resort, Wisconsin Dells, WI',
    'Offsite: The Great Wolf Lodge, Wisconsin Dells, WI',
    'Offsite: The Chula Vista Resort, Wisconsin Dells, WI',
    'Offsite: The Sundara Inn & Spa, Wisconsin Dells, WI',
    'Offsite: The Osthoff Resort, Elkhart Lake, WI',
    'Offsite: The Heidel House Hotel & Conference Center, Green Lake, WI',
    'Offsite: The Abbey Resort, Fontana-On-Geneva-Lake, WI',
    'Offsite: The Geneva National Resort & Club, Lake Geneva, WI',
    'Offsite: The Lake Lawn Resort, Delavan, WI',
    'Offsite: The Ridge Hotel, Lake Geneva, WI',
    'Offsite: The Maxwell Mansion, Lake Geneva, WI',
    'Offsite: The Baker House, Lake Geneva, WI',
    'Offsite: The Delafield Hotel, Delafield, WI',
    'Offsite: The Charmant Hotel, La Crosse, WI',
    'Offsite: The Lismore Hotel, Eau Claire, WI',
    'Offsite: The Hotel Northland, Autograph Collection, Green Bay, WI',
    'Offsite: The Lodge Kohler, Green Bay, WI',
    'Offsite: The CopperLeaf Boutique Hotel & Spa, Appleton, WI',
    'Offsite: The Jefferson Street Inn, Wausau, WI',
    'Offsite: The Radisson Hotel & Conference Center, Green Bay, WI',
    'Offsite: The Hyatt Regency Green Bay, Green Bay, WI',
    'Offsite: The KI Convention Center, Green Bay, WI',
    'Offsite: The Resch Center, Green Bay, WI',
    'Offsite: The Lambeau Field, Green Bay, WI',
    'Offsite: The Fiserv Forum, Milwaukee, WI',
    'Offsite: The American Family Field, Milwaukee, WI',
    'Offsite: The Wisconsin Center, Milwaukee, WI',
    'Offsite: The Baird Center, Milwaukee, WI',
    'Offsite: The U.S. Bank Center, Milwaukee, WI',
    'Offsite: The Northwestern Mutual Tower and Commons, Milwaukee, WI',
    'Offsite: The Johnson Controls Headquarters, Glendale, WI',
    'Offsite: The Harley-Davidson Museum, Milwaukee, WI',
    'Offsite: The Milwaukee Art Museum, Milwaukee, WI',
    'Offsite: The Discovery World, Milwaukee, WI',
    'Offsite: The Marcus Performing Arts Center, Milwaukee, WI',
    'Offsite: The Pabst Theater, Milwaukee, WI',
    'Offsite: The Riverside Theater, Milwaukee, WI',
    'Offsite: The Turner Hall Ballroom, Milwaukee, WI',
    'Offsite: The Wisconsin Club, Milwaukee, WI',
    'Offsite: The University Club of Milwaukee, Milwaukee, WI',
    'Offsite: The Milwaukee Athletic Club, Milwaukee, WI',
    'Offsite: The Tripoli Shrine Center, Milwaukee, WI',
    'Offsite: The Villa Terrace Decorative Arts Museum, Milwaukee, WI',
    'Offsite: The Charles Allis Art Museum, Milwaukee, WI',
    'Offsite: The Grohmann Museum, Milwaukee, WI',
    'Offsite: The War Memorial Center, Milwaukee, WI',
]

_COMMITTEE_ROLES = [
    'Chair', 'Vice Chair', 'Secretary', 'Member',
    'Observer', 'General Counsel', 'Advisor',
    'Lead Independent Director',
    'Co-Chair',
    'Acting Chair',
    'Chair Emeritus',
    'Recording Secretary',
    'Assistant Secretary',
    'Parliamentarian',
    'Independent Advisor',
    'External Counsel',
    'Subject Matter Expert',
    'Management Representative',
    'Presenter',
    'Guest',
    'Ex Officio Member',
    'Non-Voting Member',
    'Committee Fellow',
    'Chief Financial Officer',
    'Chief Human Resources Officer',
    'Chief Compliance Officer',
    'Chief Risk Officer',
    'Chief Information Security Officer',
    'Corporate Secretary',
    'Invited Guest',
    'Consultant',
    'Auditor',
    'Treasurer',
    'Designated Owner',
    'Sponsor',
    'Stakeholder',
    'Facilitator',
    'Proxy',
    'Alternate Member',
    'Public Member',
    'Employee Representative',
    'Chief Executive Officer',
    'Chief Operating Officer',
    'Chief Technology Officer',
    'Chief Information Officer',
    'Chief Marketing Officer',
    'Chief Revenue Officer',
    'Chief Strategy Officer',
    'Chief Legal Officer',
    'Chief People Officer',
    'Chief Diversity Officer',
    'Chief Sustainability Officer',
    'Chief Investment Officer',
    'Chief Accounting Officer',
    'Chief Data Officer',
    'Chief Analytics Officer',
    'Chief Security Officer',
    'Chief Privacy Officer',
    'Chief Ethics Officer',
    'President',
    'Executive Vice President',
    'Senior Vice President',
    'Vice President',
    'Assistant Vice President',
    'Associate Vice President',
    'Director',
    'Senior Director',
    'Associate Director',
    'Manager',
    'Senior Manager',
    'Program Manager',
    'Project Manager',
    'Team Lead',
    'Individual Contributor',
    'Principal',
    'Fellow',
    'Distinguished Engineer',
    'Distinguished Scientist',
    'Research Fellow',
    'Postdoctoral Fellow',
    'Intern',
    'Co-op',
    'Temporary Staff',
    'Contractor',
    'Consultant (External)',
    'Advisor (External)',
    'Legal Counsel (External)',
    'Auditor (External)',
    'Actuary (External)',
    'Valuation Specialist (External)',
    'Compensation Consultant (External)',
    'Governance Advisor (External)',
    'Proxy Solicitor (External)',
    'Investor Relations Advisor (External)',
    'Public Relations Advisor (External)',
    'Lobbyist (External)',
    'Government Affairs Advisor (External)',
    'Cybersecurity Advisor (External)',
    'Risk Management Advisor (External)',
    'M&A Advisor (External)',
    'Integration Advisor (External)',
    'Restructuring Advisor (External)',
    'Turnaround Advisor (External)',
    'Bankruptcy Counsel (External)',
    'Special Counsel (External)',
    'Independent Investigator (External)',
    'Monitor (External)',
    'Mediator (External)',
    'Arbitrator (External)',
    'Expert Witness (External)',
    'Facilitator (External)',
    'Executive Coach (External)',
    'Leadership Development Consultant (External)',
    'Organizational Development Consultant (External)',
    'Change Management Consultant (External)',
    'Strategy Consultant (External)',
    'Operations Consultant (External)',
    'IT Consultant (External)',
    'Digital Transformation Advisor (External)',
    'AI Strategy Advisor (External)',
    'Data Science Consultant (External)',
    'Cloud Architecture Advisor (External)',
    'Cybersecurity Consultant (External)',
    'Privacy Consultant (External)',
    'ESG Consultant (External)',
    'Sustainability Advisor (External)',
    'DEI Consultant (External)',
    'Human Rights Advisor (External)',
    'Supply Chain Consultant (External)',
    'Logistics Advisor (External)',
    'Procurement Consultant (External)',
    'Manufacturing Advisor (External)',
    'Quality Consultant (External)',
    'Safety Consultant (External)',
    'Environmental Consultant (External)',
    'Real Estate Advisor (External)',
    'Facilities Consultant (External)',
    'Marketing Advisor (External)',
    'Brand Strategy Consultant (External)',
    'Sales Consultant (External)',
    'Customer Experience Advisor (External)',
    'Product Strategy Advisor (External)',
    'Innovation Consultant (External)',
    'R&D Advisor (External)',
    'IP Strategy Advisor (External)',
    'Regulatory Affairs Advisor (External)',
    'Clinical Trial Advisor (External)',
    'Medical Affairs Advisor (External)',
    'Health Economics Advisor (External)',
    'Market Access Advisor (External)',
    'Government Pricing Advisor (External)',
    'Trade Compliance Advisor (External)',
    'Anti-Corruption Advisor (External)',
    'Sanctions Advisor (External)',
    'AML Advisor (External)',
    'Fraud Investigation Advisor (External)',
    'Forensic Accounting Advisor (External)',
    'Valuation Advisor (External)',
    'Transaction Advisory Services (External)',
    'Due Diligence Advisor (External)',
    'Post-Merger Integration Advisor (External)',
    'Carve-Out Advisor (External)',
    'Divestiture Advisor (External)',
    'Joint Venture Advisor (External)',
    'Strategic Partnership Advisor (External)',
    'Capital Allocation Advisor (External)',
    'Treasury Advisor (External)',
    'Risk Transfer Advisor (External)',
    'Insurance Broker (External)',
    'Reinsurance Broker (External)',
    'Captive Manager (External)',
    'Benefits Broker (External)',
    'Retirement Plan Advisor (External)',
    'Investment Consultant (External)',
    'OCIO Advisor (External)',
    'Pension Actuary (External)',
    'Health Actuary (External)',
    'P&C Actuary (External)',
    'Life Actuary (External)',
    'Enterprise Risk Actuary (External)',
    'Board Member',
    'Independent Director',
    'Non-Executive Director',
    'Lead Independent Director',
    'Board Chair',
    'Board Vice Chair',
    'Committee Chair',
    'Committee Vice Chair',
    'Committee Member',
    'Board Observer',
    'Board Advisor',
    'Director Emeritus',
    'Shareholder Representative',
    'Investor Representative',
    'Creditor Representative',
    'Union Representative',
    'Employee Representative',
    'Community Representative',
    'Customer Representative',
    'Supplier Representative',
    'Government Representative',
    'Regulatory Representative',
    'Academic Advisor',
    'Scientific Advisor',
    'Technical Advisor',
    'Clinical Advisor',
    'Ethical Advisor',
    'Spiritual Advisor',
]

_AGENDA_ITEM_TITLES = [
    'Quarterly Compensation Analysis \u2014 {org}',
    'Executive Salary Band Recalibration',
    'Annual Incentive Plan Performance Assessment',
    'Pay Equity Review \u2014 {industry} Job Families',
    'Benefits Renewal \u2014 Carrier Selection Update',
    'Workforce Reduction Planning \u2014 Notification Requirements',
    'Long-Term Incentive Program \u2014 Grant Cycle Approval',
    'Regulatory Update: {frameworks} Compliance Briefing',
    'Total Rewards Benchmarking \u2014 Peer Group Refresh',
    'CEO Compensation Review \u2014 Annual Assessment',
    'Retention Program \u2014 Key Employee Identification',
    'Job Architecture Redesign \u2014 Phase {q} Approval',
    'Severance Policy Amendment \u2014 Review and Vote',
    'Succession Planning Report \u2014 {org} Executive Team',
    'Annual Compensation Cycle Planning \u2014 Timeline and Budget',
    'Market Competitiveness Review \u2014 {industry} Sector',
    'Incentive Plan Design Modifications \u2014 FY {year} Proposal',
    'HRIS Platform Assessment \u2014 Vendor Selection Update',
    'Workforce Analytics Initiative \u2014 Program Status',
    'Equity Program Administration \u2014 Annual Review',
    'Cybersecurity Risk Posture Review \u2014 Q{q} Update',
    'Enterprise Risk Management Framework \u2014 Annual Assessment',
    'Financial Controls Review \u2014 SOX 404 Compliance',
    'Public Policy Priorities for FY{year}',
    'Shareholder Engagement Strategy \u2014 Proxy Season {year}',
    'ESG Materiality Assessment Results',
    'Sustainability Report {year} \u2014 Draft Review',
    'Retirement Plan Investment Performance \u2014 Q{q} Review',
    '401(k) Plan Fee Benchmarking Analysis',
    'Health and Welfare Plan Renewal Strategy for {year}',
    'Pay Equity Audit Findings and Remediation Plan',
    'Leadership Development Program ROI Analysis',
    'DEI Metrics Dashboard \u2014 Q{q} Progress Report',
    'Capital Allocation Plan for FY{year}',
    'M&A Pipeline Review \u2014 Project {project_name}',
    'Treasury Report: Cash Position and Investment Policy',
    'Review of Strategic Alternatives \u2014 Project {project_name}',
    'Internal Investigation Update \u2014 Matter {n}',
    'CEO Succession Plan Review \u2014 Emergency & Long-Term',
    'Operational Efficiency Initiative \u2014 Phase {q} Results',
    'Technology Roadmap and Investment Plan for FY{year}',
    'Corporate Strategy Refresh \u2014 {industry} Market Trends',
    'Quarterly Disclosure Review \u2014 10-Q/10-K',
    'Ethics and Compliance Program Annual Report',
    'Crisis Management Plan Test Results',
    'Data Governance Policy \u2014 Proposed Revisions',
    'Workplace Safety Incident Report \u2014 Q{q}',
    'Real Estate Portfolio Optimization Plan',
    'AI Governance Policy \u2014 Initial Draft for Review',
    'Labor Relations Update \u2014 Collective Bargaining Status',
    'Pension Plan De-Risking Strategy',
    'Healthcare Cost Containment Initiative Update',
    'Global Compensation Framework \u2014 Harmonization Progress',
    'Executive Session: CEO Performance Review',
    'Independent Director Session: Board Effectiveness',
    'Workforce Analytics Platform Demo and Proposal',
    'Compensation Philosophy Review and Update',
    'HR Technology Stack Rationalization Plan',
    'Employee Stock Purchase Plan (ESPP) Annual Review',
    'Non-Qualified Deferred Compensation Plan Funding Strategy',
    'Change-in-Control Severance Plan Review',
    'Relocation Policy Update for Remote Workforce',
    'Internal Controls Over Financial Reporting (ICFR) Assessment',
    'Business Continuity and Disaster Recovery Test Results',
    'Government Affairs Update \u2014 {regions} Legislation',
    'Charitable Contributions Budget for FY{year}',
    'Political Action Committee (PAC) Contribution Strategy',
    'Intellectual Property Portfolio Review',
    'Supply Chain Risk Assessment and Mitigation Plan',
    'Customer Advisory Board Feedback Summary',
    'Product Strategy and Roadmap for {year}',
    'Digital Transformation Program Update',
    'Regional Business Review: Americas',
    'Regional Business Review: EMEA',
    'Regional Business Review: APAC',
    'Joint Venture Performance Review \u2014 {org}',
    'Special Litigation Matter Update',
    'Executive Talent Review and Calibration',
    'Workforce Restructuring Proposal \u2014 Project {project_name}',
    'Benefits Design for {year} Open Enrollment',
    'Incentive Compensation Governance Report',
    'Sales Compensation Plan for FY{year}',
    'R&D Project Portfolio and Investment Review',
    'Corporate Security Threat Assessment',
    'Insider Trading Policy Annual Certification',
    'Records Management Policy Audit Findings',
    'Brand and Reputation Risk Assessment',
    'Approval of Prior Meeting Minutes',
    'Call to Order and Roll Call',
    'Review of Committee Charter',
    'Director Independence Assessment',
    'Conflict of Interest Disclosures',
    'Annual Committee Self-Assessment',
    'Proxy Statement Review \u2014 {year} Draft',
    'CD&A Narrative Review and Approval',
    'Peer Group Selection for {year} Benchmarking',
    'Say-on-Pay Vote Outcome Analysis',
    'Shareholder Proposal Review and Response',
    'Stock Ownership Guideline Compliance Review',
    'Anti-Hedging and Pledging Policy Review',
    'Director Compensation Benchmarking',
    'Annual Performance Goal Setting for Executive Team',
    'Clawback Policy Trigger Event Review',
    'Relative TSR Performance Calculation and Payout Certification',
    'External Auditor Independence Review',
    'Internal Audit Plan for FY{year}',
    'Whistleblower Hotline Report Summary',
    'Quarterly Financial Results Review',
    'Earnings Release and Guidance Review',
    'Dividend Policy Review',
    'Share Repurchase Program Authorization',
    'Debt Covenant Compliance Certificate',
    'Insurance Program Renewal Strategy',
    'Foreign Exchange Hedging Policy Review',
    'IT General Controls (ITGC) Audit Results',
    'Data Privacy Impact Assessment (DPIA) Report',
    'Annual Report on Form 10-K \u2014 Draft Review',
    'Quarterly Report on Form 10-Q \u2014 Draft Review',
    'Current Report on Form 8-K \u2014 Recent Filings',
]

_AGENDA_DISCUSSION_TEMPLATES = [
    '{chair} presented the {item_title} for committee review. The analysis, prepared by '
    'ACPWB engagement team, covered {n} employee records across {regions} organizational '
    'units. Discussion focused on variance from prior-year benchmarks and alignment with '
    'the {industry} peer group. Members raised questions regarding methodology and timeline '
    'for implementation. {chair} noted that all supporting documentation is available as '
    'Exhibit {exhibit} in the meeting materials.',

    'The committee received a briefing from {presenter} on the status of the {item_title}. '
    '{presenter} noted that progress has been made against the Q{q} milestones, with '
    'the majority of action items from the prior meeting resolved. Remaining open items '
    'were reviewed individually. The committee directed the responsible owner to provide '
    'a written status update no later than the due date indicated.',

    '{presenter} summarized findings from the {item_title} review, covering the period '
    'ending {date}. The committee noted {n} employees affected across {regions} locations '
    'in the {industry} sector. A motion was introduced following discussion. See motion '
    'record below. Exhibit {exhibit} contains the full supporting analysis.',

    'Following the presentation by {presenter}, the committee engaged in extended discussion '
    'regarding the {item_title}. Members raised concerns about the timeline, the scope of '
    'impact on {n} affected employees, and the potential regulatory implications. '
    '{chair} summarized the consensus view and called for a motion.',

    'The committee reviewed the {item_title} materials circulated in advance of the meeting. '
    '{presenter} was available to respond to questions. No substantive issues were raised. '
    'The committee accepted the report as presented. The responsible owner was directed to '
    'implement the recommended approach effective as of the due date.',

    'The meeting was called to order by {chair}. The primary agenda item, {item_title}, was introduced. '
    'A detailed presentation was delivered by {presenter}, outlining the key findings and recommendations '
    'as detailed in Exhibit {exhibit}. The committee members engaged in a robust Q&A session, focusing on the '
    'potential impact on {org} and the {industry} sector. The discussion concluded with a call for a formal motion.',

    'As the first order of business, {chair} requested a review of the {item_title}. {presenter} provided a '
    'verbal summary, highlighting a {pct}% variance against the plan. The committee discussed the root causes, '
    'which were attributed to unforeseen market shifts in the {industry} sector. A proposal for corrective action '
    'was put forward for a vote.',

    '{presenter} walked the committee through the {item_title} proposal. The proposal aims to address '
    'long-standing issues affecting {n} employees in the {regions} region. After a thorough debate on the '
    'budgetary impact and timeline, the committee moved to a formal resolution. All related materials were '
    'previously distributed as Exhibit {exhibit}.',

    'The {item_title} was presented by {presenter} for final approval. The plan, developed over the past '
    'quarter, has been reviewed by legal and finance. The committee\'s discussion centered on the communication '
    'strategy for the {n} affected stakeholders. A motion to approve was made and seconded.',

    '{chair} opened the floor for discussion on the {item_title}. The committee members had received the '
    'pre-read materials, including the analysis in Exhibit {exhibit}. The conversation focused on the '
    'risk assessment and mitigation plan. Following the discussion, a member of the committee proposed a '
    'motion to adopt the recommendations with minor amendments.',

    'The committee convened to address the urgent matter of the {item_title}. {presenter} provided a '
    'comprehensive overview of the situation, including its potential impact on {org}\'s operations in the '
    '{industry} sector. The committee deliberated on several response options before proceeding to a vote.',

    'The regular quarterly review of the {item_title} was led by {presenter}. The data presented in Exhibit {exhibit} '
    'showed performance to be on track with the {year} operating plan. The committee acknowledged the positive '
    'progress and accepted the report as filed, with no further action required at this time.',

    'A special session was held to review the {item_title}. {presenter} outlined the strategic rationale '
    'for the proposal, emphasizing the competitive pressures in the {industry} sector. The committee members '
    'questioned the financial assumptions and requested additional sensitivity analysis before the next meeting.',

    '{chair} noted that the primary purpose of the meeting was to vote on the {item_title}. The resolution, '
    'as drafted and circulated, was read into the record. There was minimal discussion, as the matter had been '
    'extensively debated in prior sessions. The motion was promptly moved and seconded.',

    'The committee considered the {item_title} as presented by {presenter}. The analysis in Exhibit {exhibit} '
    'highlighted a need for policy changes to align with new regulations. After discussion of the implementation '
    'challenges, the committee voted to approve the new policy framework.',

    'The {item_title} was the sole item on the agenda. {presenter} provided an in-depth briefing, after which '
    'the committee entered into an executive session for further deliberation. Upon returning to open session, '
    'a motion was made to approve the recommended course of action.',

    'The committee reviewed the quarterly performance metrics related to the {item_title}. {presenter} reported '
    'that all KPIs were within the target range, with the exception of a {pct}% shortfall in the {regions} region. '
    'A plan to address this regional variance was requested for the next meeting.',

    'The annual review of the {item_title} was conducted. {presenter} confirmed that all compliance and '
    'reporting requirements for the prior fiscal year had been met. The committee formally accepted the '
    'attestation report as filed.',

    '{chair} introduced the {item_title}, noting its importance to the company\'s strategic objectives for {year}. '
    '{presenter} presented three alternative approaches, detailed in Exhibit {exhibit}. The committee debated the '
    'merits of each before voting on the preferred option.',

    'The committee discussed the findings of the recent audit related to the {item_title}. {presenter} summarized '
    'the {n} findings and management\'s proposed remediation plan. The committee endorsed the plan and requested '
    'quarterly progress updates.',

    'A presentation on the {item_title} was given by {presenter}, our external advisor from ACPWB. The presentation '
    'benchmarked {org}\'s practices against {n} peers in the {industry} sector. The committee directed management '
    'to develop an action plan based on the findings.',

    'The committee reviewed and approved the minutes from the previous meeting held on {date}. {chair} then '
    'moved to the main agenda item, the {item_title}. {presenter} began the presentation.',

    'The {item_title} was brought to the committee for a final vote. Having been discussed at length in the '
    'prior two meetings, the chair moved directly to the resolution. The motion was carried with a majority vote.',

    'The committee received an update on the {item_title} from {presenter}. The project is currently on schedule '
    'and under budget. The next major milestone is {due_date}. No committee action was required.',

    'A special review of the {item_title} was conducted in light of the recent acquisition of {org}. {presenter} '
    'outlined the plan for harmonizing policies and systems. The committee approved the integration plan in principle, '
    'pending final due diligence.',

    'The committee deliberated on the {item_title}. The core of the discussion was the trade-off between '
    'short-term cost savings and long-term strategic investment. A consensus was reached to proceed with the '
    'phased approach outlined in Exhibit {exhibit}.',

    'The {item_title} was presented by {presenter}. The committee expressed satisfaction with the thoroughness '
    'of the analysis and the clarity of the recommendations. The motion to approve passed unanimously.',
    'The Chair, {chair}, called the meeting to order and moved to the first agenda item, {item_title}. {presenter} provided a high-level overview, referencing the detailed materials in Exhibit {exhibit}. The ensuing discussion focused on the financial implications, with several members questioning the underlying assumptions. A motion to table the item pending further analysis was proposed.',
    '{presenter} led the discussion on the {item_title}, highlighting the recent performance data for the {industry} sector. The committee noted the {pct}% deviation from the forecast and debated potential corrective measures. The consensus was to adopt a phased approach, as outlined in the revised proposal. A formal vote followed.',
    'The committee dedicated the majority of the session to the {item_title}. {presenter} facilitated a workshop-style discussion, exploring three strategic options. After a robust debate, a straw poll indicated a preference for Option B. The Chair requested a formal motion to proceed with that option.',
    'The {item_title} was introduced by {chair}. {presenter} then presented the findings of the internal audit, which identified {n} areas of non-compliance. The committee reviewed the proposed remediation plan and, after a brief discussion, moved to approve it with an accelerated timeline.',
    'The committee considered the {item_title}, a recurring item for quarterly review. {presenter} confirmed that all metrics were within acceptable tolerance levels and that no action was required. The committee accepted the report as presented.',
    'A special presentation on the {item_title} was delivered by {presenter}, an external advisor from {org}. The presentation benchmarked the company against {n} peers and identified several opportunities for improvement. The committee thanked the presenter and directed management to develop an action plan.',
    'The meeting began with a review of the minutes from the prior session, which were approved without modification. The committee then turned to the main agenda item, {item_title}. {presenter} provided a 15-minute summary, followed by a Q&A session.',
    'The {item_title} was brought before the committee for a final decision. The matter had been extensively debated in previous meetings. {chair} summarized the key arguments for and against the proposal before calling for a vote. The resolution passed by a narrow margin.',
    'An update on the progress of the {item_title} initiative was provided by {presenter}. The project is tracking ahead of schedule and under budget. The committee commended the project team for their performance and requested a final report upon completion.',
    'The committee reviewed the proposal for the {item_title}. The discussion was brief, as all members had submitted their questions in advance and received written responses. A motion to approve the proposal was made, seconded, and carried unanimously.',
    'The {item_title} was discussed in executive session due to its confidential nature. Upon returning to open session, the Chair announced that a resolution had been passed, the details of which would be communicated to relevant parties by the Corporate Secretary.',
    'The committee reviewed the {item_title} and the associated analysis in Exhibit {exhibit}. The discussion focused on the risk-reward trade-off. A motion to approve the expenditure was made, contingent on a final review by the legal department.',
    'The {item_title} was presented by {presenter}. After a short clarifying discussion, the committee members agreed that the matter was straightforward and did not require extensive debate. The motion to approve was passed without dissent.',
    'The committee received a report on the {item_title}. The data indicated a negative trend that required immediate attention. The committee formed an ad hoc subcommittee to investigate the issue and report back with recommendations at the next meeting.',
    'The {item_title} was the final item of business. {presenter} provided a brief update, noting that the project was on hold pending a decision from the executive leadership team. The committee acknowledged the update and moved to adjourn.',
    'The discussion on the {item_title} was led by {chair}. The committee reviewed the performance of the {industry} division in the {regions} region. The results were deemed unsatisfactory, and the committee requested a detailed turnaround plan from management.',
    'The committee considered the {item_title}, focusing on the compliance implications of the new {frameworks} regulation. {presenter}, the Chief Compliance Officer, recommended a series of policy updates, which were approved by the committee after a brief discussion.',
    'The {item_title} was presented by {presenter}, who outlined the proposed changes to the company\'s compensation philosophy. The committee debated the merits of moving to a more aggressive market positioning and ultimately approved a shift to the 75th percentile for critical roles.',
    'The committee reviewed the {item_title} and the associated financial model in Exhibit {exhibit}. The model projected a {pct}% return on investment over a {n}-year period. The committee approved the project, authorizing an initial budget of ${n}M.',
    'The {item_title} was a follow-up from the previous meeting. {presenter} confirmed that all action items had been completed and that the issue was now resolved. The committee formally closed the item.',
    'The committee discussed the {item_title} in the context of the company\'s long-range strategic plan. The proposal was deemed to be in alignment with the plan, and a motion to approve was made and carried.',
    'The {item_title} was presented by {presenter}, who requested an additional budget allocation of ${n}K to complete the project. The committee reviewed the request and, after a short debate, approved it.',
    'The committee reviewed the {item_title}, a proposal to enter the {regions} market. The discussion focused on the competitive landscape and the regulatory hurdles. The committee approved a budget for a feasibility study.',
    'The {item_title} was a review of the company\'s performance against its ESG goals. {presenter} reported that the company had met {n} of its {n2} targets for the year. The committee discussed strategies for addressing the shortfalls.',
    'The committee considered the {item_title}, a proposal to acquire {org}. The discussion was held in executive session. Upon returning to open session, the Chair announced that the committee had authorized management to submit a non-binding letter of intent.',
    'The {item_title} was a review of the company\'s cybersecurity posture. {presenter}, the CISO, reported on a recent penetration test, which identified {n} critical vulnerabilities. The committee approved the budget for the proposed remediation plan.',
    'The committee discussed the {item_title}, a review of the succession plan for the CEO. The discussion was held in executive session with only independent directors present.',
    'The {item_title} was a review of the company\'s DEI metrics. {presenter} reported that representation of underrepresented groups had increased by {pct}% year-over-year. The committee commended the progress but noted that more work was needed.',
    'The committee considered the {item_title}, a proposal to implement a new HRIS system. The project was approved with a total budget of ${n}M over {n2} years.',
    'The {item_title} was a review of the company\'s compliance with the {frameworks}. The committee noted {n} minor exceptions and directed management to implement corrective actions.',
    'The committee discussed the {item_title}, a proposal to launch a new product, {project_name}. The proposal was approved, and the product is scheduled to launch in Q{q} {year}.',
    'The {item_title} was a review of the company\'s brand and reputation metrics. {presenter} reported a {pct}-point increase in brand sentiment following the recent marketing campaign.',
    'The committee considered the {item_title}, a proposal to divest the {industry} business unit. The committee authorized management to engage an investment bank to explore strategic alternatives.',
    'The {item_title} was a review of the company\'s real estate portfolio. The committee approved a plan to consolidate {n} office locations, resulting in an estimated annual savings of ${n}M.',
    'The committee discussed the {item_title}, a review of the company\'s intellectual property strategy. The committee approved a budget to file {n} new patents in the coming year.',
    'The {item_title} was a review of the company\'s supply chain performance. {presenter} reported that on-time delivery rates had improved to {pct}%, a {n}-point increase from the previous quarter.',
    'The committee considered the {item_title}, a proposal to adopt a new data governance policy. The policy was approved and will be implemented company-wide over the next {n} months.',
    'The {item_title} was a review of the company\'s customer satisfaction scores. The scores had declined by {pct}% in the {regions} region. The committee requested a detailed action plan from the regional leadership team.',
    'The committee discussed the {item_title}, a review of the company\'s talent acquisition metrics. The time-to-fill for open positions had increased to {n} days, a {pct}% increase from the previous year. The committee directed HR to investigate the root causes.',
    'The {item_title} was a review of the company\'s employee benefits program. The committee approved a new parental leave policy, increasing paid leave to {n} weeks.',
    'The committee considered the {item_title}, a proposal to implement a new sales compensation plan. The plan was designed to incentivize growth in the {industry} sector and was approved by the committee.',
    'The {item_title} was a review of the company\'s performance management process. The committee approved a move to a continuous feedback model, eliminating annual performance reviews.',
    'The committee discussed the {item_title}, a review of the company\'s leadership development program. The program was found to have a positive ROI, with graduates being promoted at a rate {pct}% higher than their peers.',
    'The {item_title} was a review of the company\'s workplace safety record. The number of recordable incidents had decreased by {pct}% year-over-year. The committee commended the safety team for their efforts.',
    'The committee considered the {item_title}, a proposal to adopt a new AI ethics policy. The policy was developed in response to the company\'s increasing use of AI in its products and operations and was approved by the committee.',
    'The {item_title} was a review of the company\'s compliance with the Foreign Corrupt Practices Act (FCPA). The committee reviewed the results of a recent internal audit, which found no material weaknesses.',
    'The committee discussed the {item_title}, a review of the company\'s political and lobbying activities. The committee approved the lobbying disclosure report for the previous quarter.',
    'The {item_title} was a review of the company\'s charitable contributions. The committee approved a total of ${n}M in grants to {n2} non-profit organizations.',
    'The committee considered the {item_title}, a proposal to establish a new joint venture with {org}. The committee authorized management to proceed with negotiating a definitive agreement.',
    'The {item_title} was a review of the company\'s performance in the {regions} market. The company had gained {pct}% market share in the previous year. The committee approved a plan to increase investment in the region.',
    'The committee discussed the {item_title}, a review of the company\'s response to a recent data breach. The committee was satisfied with the response and directed the CISO to implement additional security controls.',
    'The {item_title} was a review of the company\'s compliance with the WARN Act in a recent layoff. The committee confirmed that all legal requirements had been met.',
    'The committee considered the {item_title}, a proposal to adopt a new clawback policy for executive compensation. The policy was approved and will be included in the next proxy statement.',
    'The {item_title} was a review of the company\'s compliance with Section 162(m) of the Internal Revenue Code. The committee confirmed that all executive compensation was structured to be deductible.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with Section 409A of the Internal Revenue Code. The committee confirmed that all deferred compensation plans were in compliance.',
    'The {item_title} was a review of the company\'s compliance with the Hart-Scott-Rodino Act in a recent acquisition. The committee confirmed that all filing requirements had been met.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on related-party transactions. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with the Bank Secrecy Act (BSA). The committee reviewed the results of a recent independent audit, which found no material weaknesses.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with the Office of Foreign Assets Control (OFAC) sanctions programs. The committee confirmed that the company was in compliance with all applicable sanctions.',
    'The {item_title} was a review of the company\'s compliance with the EU\'s General Data Protection Regulation (GDPR). The committee reviewed the company\'s data processing activities and confirmed that they were in compliance.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on the use of social media by employees. The policy was approved and will be included in the employee handbook.',
    'The {item_title} was a review of the company\'s compliance with the Americans with Disabilities Act (ADA). The committee reviewed the company\'s accommodation process and confirmed that it was in compliance.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with the Family and Medical Leave Act (FMLA). The committee reviewed the company\'s leave administration process and confirmed that it was in compliance.',
    'The {item_title} was a review of the company\'s compliance with the Fair Labor Standards Act (FLSA). The committee reviewed the company\'s classification of exempt and non-exempt employees and confirmed that it was in compliance.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on employee expense reimbursement. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with the Occupational Safety and Health Act (OSHA). The committee reviewed the company\'s safety record and confirmed that it was in compliance.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with the Employee Retirement Income Security Act (ERISA). The committee reviewed the company\'s administration of its employee benefit plans and confirmed that it was in compliance.',
    'The {item_title} was a review of the company\'s compliance with the Consolidated Omnibus Budget Reconciliation Act (COBRA). The committee reviewed the company\'s administration of its continuation coverage and confirmed that it was in compliance.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on employee privacy. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with the Health Insurance Portability and Accountability Act (HIPAA). The committee reviewed the company\'s handling of protected health information and confirmed that it was in compliance.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with the Sarbanes-Oxley Act (SOX). The committee reviewed the company\'s internal controls over financial reporting and confirmed that they were effective.',
    'The {item_title} was a review of the company\'s compliance with the Dodd-Frank Act. The committee reviewed the company\'s executive compensation practices and confirmed that they were in compliance.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on insider trading. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with the Securities Act of 1933. The committee reviewed the company\'s public offerings and confirmed that they were in compliance.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with the Securities Exchange Act of 1934. The committee reviewed the company\'s periodic reports and confirmed that they were in compliance.',
    'The {item_title} was a review of the company\'s compliance with the Investment Company Act of 1940. The committee reviewed the company\'s investment activities and confirmed that they were in compliance.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on corporate political activity. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with the Lobbying Disclosure Act. The committee reviewed the company\'s lobbying activities and confirmed that they were in compliance.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with the Federal Election Campaign Act. The committee reviewed the company\'s political contributions and confirmed that they were in compliance.',
    'The {item_title} was a review of the company\'s compliance with the Bipartisan Campaign Reform Act. The committee reviewed the company\'s electioneering communications and confirmed that they were in compliance.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on charitable contributions. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with the Internal Revenue Code. The committee reviewed the company\'s tax filings and confirmed that they were in compliance.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with state and local tax laws. The committee reviewed the company\'s state and local tax filings and confirmed that they were in compliance.',
    'The {item_title} was a review of the company\'s compliance with international tax laws. The committee reviewed the company\'s international tax filings and confirmed that they were in compliance.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on transfer pricing. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with customs and trade laws. The committee reviewed the company\'s import and export activities and confirmed that they were in compliance.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with environmental laws. The committee reviewed the company\'s environmental impact and confirmed that it was in compliance.',
    'The {item_title} was a review of the company\'s compliance with antitrust laws. The committee reviewed the company\'s competitive practices and confirmed that they were in compliance.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on intellectual property. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with patent laws. The committee reviewed the company\'s patent portfolio and confirmed that it was in compliance.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with trademark laws. The committee reviewed the company\'s brand portfolio and confirmed that it was in compliance.',
    'The {item_title} was a review of the company\'s compliance with copyright laws. The committee reviewed the company\'s content portfolio and confirmed that it was in compliance.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on trade secrets. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with contract laws. The committee reviewed the company\'s contracting process and confirmed that it was in compliance.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with tort laws. The committee reviewed the company\'s risk management practices and confirmed that they were in compliance.',
    'The {item_title} was a review of the company\'s compliance with criminal laws. The committee reviewed the company\'s internal controls and confirmed that they were effective in preventing criminal activity.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on corporate social responsibility. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with human rights laws. The committee reviewed the company\'s supply chain and confirmed that it was in compliance.',
    'The committee discussed the {item_title}, a review of the company\'s compliance with labor laws. The committee reviewed the company\'s employment practices and confirmed that they were in compliance.',
    'The {item_title} was a review of the company\'s compliance with consumer protection laws. The committee reviewed the company\'s marketing practices and confirmed that they were in compliance.',
    'The committee considered the {item_title}, a proposal to adopt a new policy on data security. The policy was approved and will be implemented company-wide.',
    'The {item_title} was a review of the company\'s compliance with privacy laws. The committee reviewed the company\'s handling of personal data and confirmed that it was in compliance.',
]

_RESOLUTION_TEMPLATES = [
    'RESOLVED, that the {committee} hereby approves the {item_title} as presented, '
    'effective {date}, and authorizes the designated owner to take all actions necessary '
    'to implement the foregoing.',

    'RESOLVED, that the {committee} approves the revised compensation structure for '
    '{org} as set forth in Exhibit {exhibit}, and directs management to implement '
    'the approved changes no later than {due_date}.',

    'RESOLVED, that the {committee} authorizes ACPWB to proceed with the engagement '
    'described in the materials presented, subject to the terms and conditions set forth '
    'in the engagement letter dated {date}.',

    'RESOLVED, that the {committee} defers consideration of the {item_title} to the '
    'next scheduled meeting, pending receipt of additional analysis from the responsible owner.',

    'RESOLVED, that the {committee} accepts the report presented regarding the '
    '{item_title}, and directs management to implement the corrective actions identified '
    'therein no later than {due_date}.',
    'RESOLVED, that the {committee} approves the recommended approach to {item_title} '
    'as described in Exhibit {exhibit}, subject to legal review to be completed '
    'within 15 days of this meeting.',
    'RESOLVED, that the {committee} ratifies the actions of management with respect to the {item_title} '
    'for the period ending {date}.',
    'RESOLVED, that the {committee} recommends that the full Board of Directors approve the {item_title} '
    'at its next scheduled meeting.',
    'RESOLVED, that the {committee} tables the motion regarding the {item_title} until such time as '
    'the requested supplementary data can be provided and reviewed.',
    'RESOLVED, that the {committee} endorses the strategic framework for the {item_title} and directs '
    'management to develop a detailed implementation plan for review at the next meeting.',
    'RESOLVED, that the {committee} approves the capital expenditure of up to ${n}M for the {item_title}, '
    'as detailed in the financial analysis provided in Exhibit {exhibit}.',
    'RESOLVED, that the {committee} approves the selection of {org} as the vendor for the {item_title} '
    'and authorizes management to execute the final contract.',
    'RESOLVED, that the {committee} adopts the revised {item_title} policy, which shall supersede all '
    'prior policies on this matter, effective immediately.',
    'RESOLVED, that the {committee} establishes an ad hoc subcommittee to further investigate the {item_title} '
    'and report its findings back to the full committee within 90 days.',
    'RESOLVED, that the {committee} approves the minutes of the meeting held on {date} as drafted and circulated.',
    'RESOLVED, that the {committee} finds the company to be in compliance with the requirements of {frameworks} '
    'for the fiscal year {year}, based on the attestation provided by management.',
    'RESOLVED, that the {committee} approves the annual budget for the {item_title} in the amount of ${n}M for fiscal year {year}.',
    'RESOLVED, that the {committee} authorizes the retention of external counsel to advise on the {item_title}.',
    'RESOLVED, that the {committee} approves the grant of {n} performance share units to the executive team, '
    'subject to the performance conditions outlined in Exhibit {exhibit}.',
    'RESOLVED, that the {committee} approves the {year} annual report on Form 10-K for filing with the SEC.',
    'RESOLVED, that the {committee} has reviewed and discussed the quarterly financial statements with management '
    'and the independent auditors.',
    'RESOLVED, that the {committee} recommends the appointment of {org} as the company\'s independent registered '
    'public accounting firm for the fiscal year ending {date}.',
    'RESOLVED, that the {committee} approves the company\'s response to the shareholder proposal regarding {item_title}.',
    'RESOLVED, that the {committee} determines that the compensation for the Named Executive Officers for fiscal year {year} '
    'is reasonable and in the best interests of the company and its shareholders.',
    'RESOLVED, that the {committee} approves the public disclosure of the {item_title} in the company\'s upcoming '
    'proxy statement.',
    'RESOLVED, that the {committee} authorizes a share repurchase program of up to ${n}M of the company\'s common stock.',
    'RESOLVED, that the {committee} declares a quarterly dividend of ${n} per share, payable on {date} to shareholders '
    'of record as of {due_date}.',
    'RESOLVED, that the meeting be adjourned.',
    'RESOLVED, that the {committee} shall enter into executive session to discuss confidential matters.',
    'RESOLVED, that the {committee} approves the formation of a new subsidiary, {org}, to pursue the {item_title}.',
    'RESOLVED, that the {committee} approves the divestiture of the {industry} business unit to {org} for a total '
    'consideration of ${n}M.',
    'RESOLVED, that the {committee} approves the company\'s ESG report for publication and distribution to stakeholders.',
]

_MOTION_VERBS = [
    'To approve', 'To defer', 'To authorize', 'To accept',
    'To ratify', 'To table', 'To adopt', 'To endorse',
    'To recommend', 'To reject', 'To amend', 'To establish',
    'To terminate', 'To investigate', 'To appoint', 'To confirm',
    'To direct', 'To instruct', 'To delegate', 'To certify',
    'To declare', 'To find', 'To determine', 'To conclude',
    'To consent', 'To concur', 'To acknowledge', 'To receive and file',
    'To proceed', 'To suspend', 'To reconsider', 'To rescind',
    'To refer to subcommittee', 'To enter executive session', 'To adjourn',
    'To approve as amended', 'To adopt with modifications', 'To ratify as corrected',
    'To authorize, subject to conditions', 'To endorse in principle',
    'To take under advisement', 'To note for the record',
    'To approve for filing',
    'To approve for release',
    'To approve for publication',
    'To approve for distribution',
    'To approve for execution',
    'To approve for submission',
    'To approve for implementation',
    'To approve for funding',
    'To approve for development',
    'To approve for acquisition',
    'To approve for divestiture',
    'To approve for partnership',
    'To approve for investment',
    'To approve for launch',
    'To approve for expansion',
    'To approve for entry',
    'To approve for exit',
    'To approve for response',
    'To approve for mitigation',
    'To approve for exploitation',
    'To approve for compliance',
    'To approve for adoption',
    'To approve for implementation',
    'To approve for development',
    'To approve for building',
    'To approve for protection',
    'To approve for monetization',
    'To approve for leveraging',
    'To approve for optimization',
    'To approve for automation',
    'To approve for digitization',
    'To approve for modernization',
    'To approve for transformation',
    'To approve for innovation',
    'To approve for reinvention',
    'To approve for disruption',
    'To approve for entry',
    'To approve for expansion',
    'To approve for consolidation',
    'To approve for restructuring',
    'To approve for turnaround',
    'To approve for growth',
    'To approve for profitability',
    'To approve for market share',
    'To approve for customer loyalty',
    'To approve for employee retention',
    'To approve for talent attraction',
    'To approve for leadership development',
    'To approve for succession planning',
    'To approve for board effectiveness',
    'To approve for shareholder value',
    'To approve for stakeholder capitalism',
    'To approve for public trust',
    'To approve for corporate reputation',
    'To approve for brand equity',
    'To approve for customer lifetime value',
    'To approve for competitive advantage',
    'To approve for sustainable growth',
    'To approve for quarterly performance',
    'To approve for annual results',
    'To approve for long-range outlook',
    'To approve for progress',
    'To approve for status',
    'To approve for update',
    'To approve for report',
    'To approve for analysis',
    'To approve for findings',
    'To approve for recommendations',
    'To approve for action plan',
    'To approve for next steps',
    'To approve for decision',
    'To approve for vote',
    'To approve for approval',
    'To approve for authorization',
    'To approve for budget',
    'To approve for headcount',
    'To approve for resources',
    'To approve for timeline',
    'To approve for milestones',
    'To approve for KPIs',
    'To approve for metrics',
    'To approve for goals',
    'To approve for objectives',
    'To approve for priorities',
    'To approve for strategy',
    'To approve for vision',
    'To approve for mission',
    'To approve for values',
    'To approve for purpose',
    'To approve for goal',
    'To approve for objective',
    'To approve for target',
    'To approve for KPI',
]

_ACTION_ITEM_TEMPLATES = [
    'Distribute approved {item_title} documentation to all affected managers',
    'Schedule follow-up briefing with {org} executive team on implementation timeline',
    'Prepare Exhibit {exhibit} addendum incorporating committee feedback from this meeting',
    'Coordinate with Legal on {frameworks} disclosure requirements and filing deadlines',
    'Circulate draft revised policy language for committee review prior to next meeting',
    'Compile Q{q} status update on open corrective action items from prior meetings',
    'Engage external counsel to review {item_title} for regulatory compliance',
    'Update benchmarking database with approved peer group changes for {industry} sector',
    'Notify affected employees of compensation changes in advance of effective date',
    'Prepare board-level summary of {item_title} for inclusion in quarterly reporting package',
    'Reconcile payroll records for affected employees and confirm accuracy with HR',
    'File required regulatory disclosures with applicable agencies by statutory deadline',
    'Distribute meeting minutes to all committee members within 5 business days',
    'Confirm vendor contract terms for benefits renewal and report back to committee chair',
    'Draft a communication plan for the rollout of the new {item_title}',
    'Provide a detailed budget breakdown for the proposal in Exhibit {exhibit}',
    'Obtain a third-party fairness opinion for the proposed transaction',
    'Conduct a sensitivity analysis on the financial projections for the {item_title}',
    'Update the committee charter to reflect new responsibilities regarding {frameworks}',
    'Benchmark the proposed severance packages against the updated peer group',
    'Develop a project plan and timeline for the {item_title} initiative',
    'Meet with institutional investors to discuss the company\'s position on {item_title}',
    'Finalize the performance metrics for the {year} executive incentive plan',
    'Review and update the company\'s stock ownership guidelines',
    'Prepare a response to the shareholder proposal on {item_title}',
    'Conduct a post-implementation review of the new HRIS platform',
    'Assess the tax implications of the proposed deferred compensation plan changes',
    'Provide the committee with a summary of recent enforcement actions related to {frameworks}',
    'Organize a board education session on emerging ESG trends',
    'Revise the annual D&O questionnaire to include new disclosure requirements',
    'Present a competitive analysis of the {industry} market at the next meeting',
    'Work with the independent auditor to scope the Q{q} review',
    'Develop a dashboard for tracking key DEI metrics',
    'Finalize the agenda for the upcoming annual shareholder meeting',
    'Conduct due diligence on the potential acquisition target, {org}',
    'Prepare a draft of the {year} Compensation Discussion and Analysis (CD&A)',
    'Model the financial impact of the proposed changes to the health plan',
    'Review the company\'s insider trading policy and recommend updates',
    'Schedule a meeting with the proxy advisory firms (ISS and Glass Lewis)',
    'Analyze the impact of the new accounting standard on financial reporting',
    'Update the enterprise risk map to include emerging geopolitical risks',
    'Provide a summary of employee feedback from the recent pulse survey',
    'Draft a board resolution to approve the capital allocation plan',
    'Coordinate with the communications team on the earnings release press release',
    'Review and approve the Form 10-Q for the quarter ending {date}',
    'Initiate the search for a new independent director with expertise in {industry}',
    'Evaluate vendors for the new compliance management system',
    'Prepare a summary of the new {frameworks} regulations for the full board',
    'Conduct a tabletop exercise for the company\'s crisis management plan',
    'Finalize the clawback calculation for the former CEO',
    'Review the company\'s data privacy policy for compliance with CPRA and GDPR',
    'Provide an update on the status of the internal investigation, Matter {n}',
    'Develop a set of KPIs for the new {item_title} initiative',
    'Analyze the cost-benefit of outsourcing the payroll function',
    'Prepare a presentation on the company\'s cybersecurity posture',
    'Review the succession plan for the top {n} executive positions',
    'Benchmark the company\'s parental leave policy against the {industry} sector',
    'Draft a response to the recent media inquiry regarding {item_title}',
    'Finalize the grant agreements for the {year} LTI awards',
    'Provide a legal opinion on the proposed restructuring plan',
    'Update the committee on the progress of the collective bargaining negotiations',
    'Conduct a compliance audit of the company\'s political contributions',
    'Review the company\'s insurance coverage for D&O and cyber liability',
    'Prepare a report on the ROI of the company\'s wellness programs',
    'Evaluate the effectiveness of the company\'s whistleblower hotline',
    'Develop a training module for managers on the new performance management process',
    'Provide a list of potential candidates for the open committee seat',
    'Analyze the impact of currency fluctuations on international operations',
    'Review and update the company\'s records retention schedule',
    'Prepare a summary of the company\'s intellectual property portfolio',
    'Conduct a market check on the fees paid to the external auditor',
    'Draft a new policy on the ethical use of artificial intelligence',
    'Provide an update on the integration progress of the recent acquisition of {org}',
    'Review the company\'s travel and expense policy for cost-saving opportunities',
    'Benchmark the company\'s ESG rating against its peer group',
    'Prepare a communication for employees regarding the upcoming open enrollment period',
    'Finalize the charter for the newly formed {item_title} subcommittee',
    'Provide a demonstration of the new workforce analytics dashboard',
    'Review the company\'s dividend policy in light of recent financial performance',
    'Analyze the potential impact of the proposed carbon tax legislation',
    'Prepare a summary of the company\'s real estate lease obligations',
    'Conduct a review of the company\'s brand reputation and social media sentiment',
    'Finalize the agenda and materials for the board strategy offsite',
    'Model the impact of proposed {frameworks} on the {year} LTI plan design',
    'Review the peer group selection methodology for the upcoming {item_title}',
    'Draft talking points for the CEO regarding the {item_title} for the earnings call',
    'Analyze the effectiveness of the current sales compensation plan in the {regions} region',
    'Prepare a competitive assessment of {org}\'s benefits package for the {industry} sector',
    'Develop a business case for the proposed HRIS platform investment',
    'Conduct a review of the company\'s data classification and handling policy',
    'Finalize the quarterly risk report for the Audit Committee',
    'Prepare a summary of the latest proxy advisor guidance on {item_title}',
    'Review and update the company\'s crisis communication plan',
    'Model the financial impact of various interest rate scenarios on the company\'s debt portfolio',
    'Draft a proposal for a new employee recognition program',
    'Assess the feasibility of implementing a new performance management framework',
    'Conduct a market analysis of compensation trends for AI and machine learning talent',
    'Prepare a presentation on the company\'s ESG performance for the investor relations team',
    'Review the company\'s compliance with new pay transparency laws in {regions} states',
    'Develop a plan for communicating changes to the employee benefits plan',
    'Analyze the cost-effectiveness of the current talent acquisition channels',
    'Prepare a report on the diversity of the leadership pipeline',
    'Review the company\'s policy on employee use of social media',
    'Conduct a review of the company\'s business continuity plan',
    'Model the impact of proposed tariff changes on the company\'s supply chain costs',
    'Draft a new policy on the ethical use of employee data and analytics',
    'Prepare a summary of recent shareholder activism trends in the {industry} sector',
    'Review the company\'s compliance with the latest cybersecurity regulations',
    'Develop a plan for improving the employee onboarding experience',
    'Analyze the ROI of the company\'s leadership development programs',
    'Prepare a report on the company\'s progress against its DEI goals',
    'Review the company\'s policy on flexible work arrangements',
    'Conduct a review of the company\'s travel and expense policy',
    'Model the impact of a potential economic downturn on the company\'s sales forecast',
    'Draft a proposal for a new employee stock purchase plan (ESPP)',
    'Assess the company\'s readiness for the upcoming {frameworks} compliance deadline',
    'Conduct a market analysis of emerging trends in employee benefits',
    'Prepare a presentation on the company\'s talent retention strategy',
    'Review the company\'s compliance with the latest data privacy laws (GDPR, CCPA)',
    'Develop a plan for improving manager effectiveness and training',
    'Analyze the results of the latest employee engagement survey',
    'Prepare a report on the company\'s succession planning for critical roles',
    'Review the company\'s policy on employee political contributions and activities',
    'Conduct a review of the company\'s intellectual property portfolio',
    'Model the impact of a potential acquisition on the company\'s financial statements',
    'Draft a new policy on the use of generative AI tools by employees',
    'Prepare a summary of recent changes to executive compensation disclosure rules',
    'Review the company\'s compliance with the latest environmental regulations',
    'Develop a plan for improving the company\'s employer brand and reputation',
    'Analyze the effectiveness of the company\'s internal mobility program',
    'Prepare a report on the company\'s progress on its sustainability initiatives',
    'Review the company\'s policy on employee health and safety',
    'Conduct a review of the company\'s vendor risk management program',
    'Model the impact of a potential divestiture on the company\'s operating model',
    'Draft a proposal for a new long-term incentive plan design',
    'Assess the company\'s compliance with the latest anti-corruption laws (FCPA, UK Bribery Act)',
    'Conduct a market analysis of executive compensation trends in the {industry} sector',
    'Prepare a presentation on the company\'s digital transformation strategy',
    'Review the company\'s compliance with the latest trade and sanctions regulations',
    'Develop a plan for improving the company\'s customer experience scores',
    'Analyze the results of the latest pulse survey on employee morale',
    'Prepare a report on the company\'s real estate portfolio optimization',
    'Review the company\'s policy on employee data retention',
    'Conduct a review of the company\'s IT disaster recovery plan',
    'Model the impact of a potential share repurchase program',
    'Draft a new policy on the company\'s approach to stakeholder engagement',
    'Prepare a summary of recent developments in corporate governance best practices',
    'Review the company\'s compliance with the latest accessibility standards (ADA, WCAG)',
    'Develop a plan for improving the company\'s innovation pipeline',
    'Analyze the effectiveness of the company\'s marketing and advertising spend',
    'Prepare a report on the company\'s progress on its digital ethics initiatives',
    'Review the company\'s policy on employee background checks and screening',
    'Conduct a review of the company\'s supply chain resilience',
    'Model the impact of a potential change in the corporate tax rate',
    'Draft a proposal for a new employee wellness program',
    'Assess the company\'s compliance with the latest financial reporting standards',
    'Conduct a market analysis of emerging technologies in the {industry} sector',
    'Prepare a presentation on the company\'s competitive landscape',
    'Review the company\'s compliance with the latest labor and employment laws',
    'Develop a plan for improving the company\'s operational efficiency',
    'Analyze the results of the latest customer feedback survey',
    'Prepare a report on the company\'s progress on its quality management initiatives',
    'Review the company\'s policy on employee conflicts of interest',
    'Conduct a review of the company\'s enterprise risk management framework',
    'Model the impact of a potential change in foreign exchange rates',
    'Draft a new policy on the company\'s approach to corporate social responsibility',
]
