# Generated by Django 5.2.12 on 2026-03-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplePageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'People Page Visit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('title', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('avatar_seed', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='people.peoplepagevisit')),
            ],
            options={
                'verbose_name': 'Generated Employee',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
