# Generated by Django 5.2.12 on 2026-03-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplepagevisit',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
    ]
