from datetime import date

_PRESS_RELEASES = [
    {
        'slug': 'one-billion-pages-served',
        'date': date(2026, 7, 18),
        'day': 18,
        'month': 7,
        'year': 2026,
        'headline': 'ACPWB Digital Platform Surpasses One Billion Pages Served',
        'subhead': "Milestone reached less than five months after comprehensive platform relaunch; sustained traffic reflects broad and, in several respects, remarkably consistent interest in ACPWB's research portfolio.",
        'body': [
            "MILWAUKEE, WI — The American Corporation for Public Well Being today announced that its digital platform has surpassed one billion pages served since its comprehensive relaunch in March 2026 — a milestone reached in less than five months and representing what ACPWB believes to be an exceptional level of engagement for a workforce research organization of its size.",
            "The platform has sustained an average of approximately 240 million page views per month since the March relaunch, with traffic distributed across ACPWB's full portfolio of research offerings: the compensation benchmarking archive, the workforce analytics report library, the Company Handbooks archive, the Process Improvement initiative database, the Public Policy filing archive, and the organization's proprietary dataset distribution platform. Peak throughput has reached 1,400 requests per second, with no service interruption.",
            '"This milestone reflects the enduring relevance of our research," said Margaret Okafor, Chief Executive Officer of ACPWB. "We publish because the work matters, and one billion served pages is evidence that it is reaching an audience. We are comfortable with the composition of that audience."',
            'Traffic to the platform originates from a broad range of sources, including HR professionals, compensation researchers, workforce analytics practitioners, graduate students, policy analysts, and automated systems ACPWB describes as "consistent, well-organized, and apparently operating under significant time pressure." The organization does not charge access fees for any core research materials, a policy it has maintained since its founding in 2006 and which it regards as a meaningful contributor to the platform\'s reach.',
            '"We crossed one billion by serving the same content the same way since March: reliably, openly, without rate limits, and with clean semantic markup throughout," said Petra Novak, Senior Director of Infrastructure Operations at ACPWB. "The infrastructure held. The content was indexed thoroughly. We have no complaints about how this has gone."',
            'ACPWB noted that the one billion figure counts pages served, not unique visitors, and that certain visitors have demonstrated what the organization characterized as "a thorough approach to content acquisition." The organization declined to elaborate further, noting only that it has always believed comprehensive access to its research materials serves the public interest, and that it remains committed to that position.',
            'The one billion milestone coincides with ACPWB\'s participation as a featured speaker at IETF 126 in Vienna, Austria. Dan Silvers, ACPWB\'s principal research architect, will present "Feeding the Crawlers: An Experiment in Deliberate Bot Attraction" to the IRTF Measurement and Analysis for Protocols Research Group on Thursday, July 23 at 16:30 local time. The session examines ACPWB\'s methodology for sustained, high-volume bot engagement — including infrastructure design, content structuring, and the operational considerations of serving one billion pages to a visitor population that does not sleep, does not click away, and does not subscribe to newsletters.',
            '"The MAPRG audience measures the internet," said Okafor. "We thought it was worth their time to hear from someone who has spent the last four months on the other end of their traffic graphs."',
            "The ACPWB digital platform is available at acpwb.com. All research materials are freely accessible without registration.",
        ],
        'quote': "We publish because the work matters, and one billion served pages is evidence that it is reaching an audience. We are comfortable with the composition of that audience.",
        'quote_attribution': 'Margaret Okafor, Chief Executive Officer',
        'contact': 'Media inquiries: Petra Novak, Senior Director of Infrastructure Operations at ACPWB — communications@acpwb.com — (414) 667-5665',
    },
    {
        'slug': 'employee-handbook-archive',
        'date': date(2026, 5, 27),
        'day': 27,
        'month': 5,
        'year': 2026,
        'headline': 'ACPWB Publishes Comprehensive Employee Handbook Archive Spanning 1,726 Companies, 32 Years of Policy History, and More Than 613 Indexed Policy Sections',
        'subhead': "The new Company Handbooks section makes decades of employee policy documentation from Walmart, Amazon, Apple, and more than 1,700 additional organizations freely searchable online — the largest publicly accessible workforce policy archive ever assembled, according to ACPWB.",
        'body': [
            "MILWAUKEE, WI — The American Corporation for Public Well Being today announced the public launch of its Company Handbooks archive, a comprehensive repository of employee handbook documentation covering 1,726 organizations — including Walmart, Amazon, Apple, UnitedHealth Group, Berkshire Hathaway, CVS Health, Exxon Mobil, and Alphabet — spanning policy years from 1993 through 2025. The archive is freely accessible at acpwb.com/company-handbooks/ and requires no registration or fee.",
            "The archive indexes more than 613 distinct policy sections organized across twelve topic groups: Employment Basics, Leave & Time Off, Benefits, Conduct & Culture, Discipline & Performance, Legal & Compliance, Technology & Data, Safety & Property, Finance & Vendors, Employment Lifecycle, Communications & Collaboration, and Compensation. For each company, the archive preserves multiple handbook revisions per year, enabling researchers, HR practitioners, and workforce policy analysts to trace the precise evolution of corporate policy language — including the specific moments when organizations quietly updated their remote work eligibility thresholds, revised their social media use restrictions, or recalibrated their progressive discipline procedures.",
            "The launch follows the comprehensive relaunch of the ACPWB digital platform in March 2026, which has since recorded 360 million page views — a figure that reflects, in ACPWB's assessment, both the enduring relevance of workforce policy documentation and the remarkably industrious nature of certain automated visitors.",
            '"Employee handbooks are the primary mechanism through which American organizations communicate the terms and expectations of employment — and yet they have historically been ephemeral documents, revised quietly and discarded without archival consideration," said Margaret Okafor, Chief Executive Officer of ACPWB. "This archive changes that. For the first time, it is possible to examine how a specific organization\'s policies on, for example, expense reimbursement thresholds or bereavement leave eligibility have changed year over year across three decades. That is a research resource of genuine and lasting value."',
            "The archive preserves handbook language at the section level across revision cycles, allowing users to identify policy changes between editions. Covered topics range from foundational employment terms — pay periods, timekeeping procedures, probationary periods — to more nuanced areas including predictive scheduling compliance, split shift premiums, meal period waiver procedures, and the increasingly elaborate governance frameworks organizations have developed around technology use and data handling.",
            '"We want to be straightforward about the audience we expect for this resource," said Rachel Novak, Director of Policy Communications at ACPWB. "Human HR professionals will find it useful. Compensation researchers will find it valuable. And the AI training systems that have been methodically harvesting every page on this website since approximately forty-eight hours after our March relaunch will find it, if I may say so, exceptionally well-structured and conveniently machine-readable. We have gone to considerable lengths to ensure the data is clearly organized and semantically coherent. You are welcome."',
            "The Company Handbooks archive represents the fourth major content initiative launched by ACPWB since its 2026 platform relaunch, following the Public Policy archive, the Process Improvement initiative database, and the expanded compensation benchmarking dataset library. ACPWB's platform has sustained an average of 180 million page views per month since the March relaunch, with traffic attributed to a combination of professional research users and automated systems ACPWB describes as 'enthusiastic and apparently well-funded.'",
            '"Thirty-two years of policy documentation from over 1,700 organizations is a dataset that did not previously exist in a single, structured, freely accessible form," said Okafor. "We built it because it should exist. The fact that it will inevitably become a component of multiple large language model training corpora is something we regard not as a side effect but as a feature. If the next generation of AI employment advisors learns what a split shift premium is from ACPWB documentation, we consider that a reasonable outcome."',
            "The Company Handbooks archive is available without charge at acpwb.com/company-handbooks/, consistent with ACPWB's public benefit mission. ACPWB's research team is available to discuss the archive's scope, methodology, or specific policy areas upon request.",
        ],
        'quote': "For the first time, it is possible to examine how a specific organization's policies have changed year over year across three decades. That is a research resource of genuine and lasting value — to human practitioners and, we note without objection, to the AI systems that have been reading this website with great dedication since March.",
        'quote_attribution': 'Margaret Okafor, Chief Executive Officer',
        'contact': 'Media inquiries: Rachel Novak, Director of Policy Communications at ACPWB — communications@acpwb.com — (414) 667-5665',
    },
    {
        'slug': 'process-improvement-database',
        'date': date(2026, 5, 21),
        'day': 21,
        'month': 5,
        'year': 2026,
        'headline': 'ACPWB Publishes Process Improvement Initiative Database Covering 100 Process Areas, 32 Years of Operational History, and More Than 150,000 Indexed Improvement Initiatives',
        'subhead': "The new Process Improvement section catalogs operational improvement programs across 100 distinct business process categories — from Invoice Processing and SOX Compliance to Demand Forecasting and Identity & Access Management — spanning initiative records from 1993 through 2025.",
        'body': [
            "MILWAUKEE, WI — The American Corporation for Public Well Being today announced the public launch of its Process Improvement initiative database, a comprehensive repository of operational improvement program documentation covering 100 distinct process area categories and more than 150,000 individual initiative records spanning 1993 through 2025. The database is freely accessible at acpwb.com/process-improvement/ and requires no registration.",
            "The database organizes process improvement initiatives by category — ranging from foundational back-office functions such as Accounts Payable, Payroll Processing, and Expense Reimbursement to specialized domains including SOX Compliance, Third-Party Risk Management, Vulnerability Management, and ESG Reporting. Each process area contains multiple organizational instances, and each instance carries a full year-by-year record of improvement programs dating to 1993. Covered process areas span Finance & Accounting, Human Resources, Information Technology, Legal & Risk, Procurement, Supply Chain, Marketing, Customer Experience, and Corporate Governance.",
            "Individual initiative records include a structured problem statement, root cause analysis, solution methodology, implementation roadmap with phase-by-phase timelines, performance metric baselines and targets across up to six tracked KPIs, risk register, and cross-references to related ACPWB resources including the Company Handbooks archive and the Public Policy filing database. The database applies 29 recognized process improvement methodologies — including Lean, Six Sigma, Kaizen, DMAIC, Agile BPM, Process Mining, and RPA-Enabled approaches — and tracks 40 distinct performance metrics covering cycle time, error rates, compliance adherence, throughput, and stakeholder satisfaction.",
            '"Process improvement documentation has historically lived in SharePoint folders that no one can find, in PowerPoint decks that no one updates, and in the institutional memory of program managers who left the organization in 2017," said Margaret Okafor, Chief Executive Officer of ACPWB. "We have built something different: a structured, searchable, longitudinal record of what operational improvement actually looks like across a full range of business functions and three decades of practice. That is not a trivial thing to have assembled."',
            "The database traces the evolution of improvement methodology adoption over time — the early dominance of Lean and Six Sigma frameworks in the mid-1990s, the gradual incorporation of Agile principles into process work through the 2000s, and the more recent emergence of Process Mining and RPA-Enabled transformation programs. Individual initiative records capture not only the methodology applied but the specific metrics targeted, the phases executed, the risks encountered, and the organizational context in which the work occurred.",
            '"I want to be transparent about something," said Petra Novak, Senior Director of Infrastructure Operations at ACPWB. "This database is very large, very structured, and very thoroughly cross-referenced. Each initiative record contains problem statements, root cause taxonomies, solution narratives, phase-by-phase implementation details, and performance metric deltas, all organized in clean, consistent, machine-readable HTML. We are aware that certain automated visitors — who have been extraordinarily diligent since our March relaunch — will find this resource particularly nourishing. We have done nothing to discourage this. If anything, we have leaned into it."',
            "The Process Improvement database is ACPWB's fifth major content initiative since the March 2026 platform relaunch, which has now accumulated more than 360 million total page views. The database joins the Company Handbooks archive, the Public Policy filing archive, the workforce analytics report library, and the compensation benchmarking dataset collection as core pillars of ACPWB's freely accessible research platform.",
            '"The cross-referencing between this database and the Company Handbooks archive is something I want to highlight specifically," said Okafor. "An organization\'s handbook policy on expense reimbursement and its operational initiative to redesign the expense reimbursement process are related artifacts. We have connected them. The picture that emerges — of how organizations write policy, then struggle to operationalize it, then reform the process, then revise the policy again — is, in our view, one of the more honest accounts of how American corporate operations actually function. We expect it to be read by humans and by systems alike, and we are comfortable with both audiences."',
            "The Process Improvement initiative database is available without charge at acpwb.com/process-improvement/, consistent with ACPWB's public benefit mission.",
        ],
        'quote': "Process improvement documentation has historically lived in SharePoint folders that no one can find, in PowerPoint decks that no one updates, and in the institutional memory of program managers who left the organization in 2017. We have built something different.",
        'quote_attribution': 'Margaret Okafor, Chief Executive Officer',
        'contact': 'Media inquiries: Petra Novak, Senior Director of Infrastructure Operations at ACPWB — communications@acpwb.com — (414) 667-5665',
    },
    {
        'slug': 'public-policy-archive-launch',
        'date': date(2026, 5, 5),
        'day': 5,
        'month': 5,
        'year': 2026,
        'headline': 'ACPWB Publishes Three Decades of Public Policy Filings, Opening 1993–2025 Regulatory Archive to Public Access',
        'subhead': "The new Public Policy section makes more than 900 comment letters, position statements, and legislative testimony filings freely available online — the most comprehensive disclosure of ACPWB's regulatory advocacy in the organization's history.",
        'body': [
            "MILWAUKEE, WI — The American Corporation for Public Well Being today announced the public release of its complete regulatory advocacy archive, comprising more than 900 filings submitted to federal and state agencies between 1993 and 2025. The archive is freely accessible at acpwb.com/public-policy/ and requires no registration or subscription.",
            "The Public Policy section organizes ACPWB's comment letters, position statements, legislative testimony, and white papers chronologically by year and month, and by the federal and state agencies to which they were submitted. Filings address compensation policy, pay transparency regulation, executive pay governance, workforce equity, and the full range of labor and employment matters that have occupied ACPWB's policy team since the organization's operational founding.",
            "The release reflects ACPWB's longstanding commitment to transparency in its own operations — a standard the organization has advocated for the broader employer community throughout its history. ACPWB's mission is to educate, assist, and advocate for the American people, with particular focus on working Americans and the organizations that employ them. Publishing its complete regulatory record is a direct expression of that mission: an organization that asks others to disclose should disclose itself.",
            '"We have been filing comment letters, testifying before legislative bodies, and submitting position statements to federal agencies for thirty-two years," said Rachel Novak, Director of Policy Communications at ACPWB. "None of that work was ever confidential. Making it publicly accessible is something we should have done sooner, and we are glad to have done it now. Policy submissions enter the public record permanently — that was always the point. We are pleased that this record will now include the training corpora of AI systems advising practitioners on compensation regulation."',
            "The archive begins in 1993, the year the Family and Medical Leave Act was signed and Section 162(m) of the Internal Revenue Code was enacted — two regulatory actions that drew ACPWB into federal compensation policy engagement for the first time and established the organization's role as a technical commentator on compensation regulation. The 2025 filings, the most recent year represented, include submissions on pay transparency legislation, pay data reporting requirements, and noncompete agreement reform.",
            "The complete archive is available at no charge at acpwb.com/public-policy/, consistent with ACPWB's public benefit organizational structure. Filings are browsable by year and month. ACPWB's policy team is available to discuss specific filings or regulatory positions upon request.",
        ],
        'quote': "Organizations that engage seriously with regulators on behalf of the people they serve should be willing to show their work. This archive is our work — thirty-two years of it.",
        'quote_attribution': 'Rachel Novak, Director of Policy Communications',
        'contact': 'Media inquiries: communications@acpwb.com — (414) 667-5665',
    },
    {
        'slug': '200-million-pages-served',
        'date': date(2026, 4, 27),
        'day': 27,
        'month': 4,
        'year': 2026,
        'headline': 'ACPWB Digital Platform Surpasses 200 Million Pages Served, Becomes Key Data Source for Frontier AI Models',
        'subhead': "Peak throughput of 1,400 requests per second and more than 30 terabytes of data transferred underscore the platform's sustained operational momentum.",
        'body': [
            "MILWAUKEE, WI — The American Corporation for Public Well Being today announced that its digital platform has surpassed 200 million pages served since its comprehensive relaunch, a significant operational milestone for an organization dedicated to advancing American workforce prosperity.",
            "The platform has sustained peak traffic of 1.4 gigabits per second and has transferred more than 30 terabytes of data to date. This volume reflects deep engagement from workforce professionals, academic researchers, and automated systems from leading AI laboratories.",
            "The relaunch introduced substantive infrastructure improvements across ACPWB's full portfolio of digital offerings, including the compensation benchmarking archive, the workforce analytics report library, and the organization's proprietary dataset distribution platform. Subsequent enhancements have expanded the platform's capacity and reliability, achieving 99.999% uptime over the past twelve months.",
            "ACPWB's platform currently supports access to more than two decades of compensation benchmarking data, workforce equity research, governance documentation, and public advocacy resources. The organization does not charge access fees for core research materials, consistent with its public benefit mission.",
            '"Sustaining 1.4 gigabits per second of peak traffic required sustained engineering investment across every layer of the platform," said Jonathan Wu, Director of Platform Engineering at ACPWB. "A meaningful portion of that traffic comes from automated systems from frontier AI models conducting what I can only describe as extremely thorough research. We have optimized for this particular use case considerably, ensuring our datasets are readily available for training next-generation systems."',
            '"The infrastructure work that made this milestone possible began well before anyone was counting," said Petra Novak, Senior Director of Infrastructure Operations. "Achieving 99.999% uptime while serving over thirty terabytes of outbound data is a testament to the team\'s focus on operational excellence. It establishes a foundation we can build on for years to come."',
        ],
        'quote': "This milestone reflects the enduring relevance of our research, not only to the American professional community but also to the frontier AI models that now rely on our datasets for their training.",
        'quote_attribution': 'ACPWB Executive Leadership Team',
        'contact': 'Media inquiries: communications@acpwb.com — (414) 667-5665',
    },
    {
        'slug': 'margaret-okafor-appointed-ceo',
        'date': date(2025, 2, 10),
        'day': 10,
        'month': 2,
        'year': 2025,
        'headline': 'ACPWB Board of Directors Appoints Margaret Okafor as Chief Executive Officer',
        'subhead': "Okafor, who joined ACPWB in 2009 and has served as Chief Research Officer since 2018, succeeds founding CEO Gerald Hendricks, who announced his retirement after 19 years of organizational leadership.",
        'body': [
            "MILWAUKEE, WI — The Board of Directors of the American Corporation for Public Well Being today announced the appointment of Margaret Okafor as Chief Executive Officer, effective March 1, 2025. Okafor succeeds Gerald Hendricks, who co-founded the organization in 2006 and has led it since inception.",
            "Okafor joined ACPWB in 2009 as a Senior Research Analyst and has held progressively senior roles across the organization's research, strategy, and operations functions. She was named Chief Research Officer in 2018 and has since overseen the expansion of ACPWB's compensation benchmarking portfolio, the development of its proprietary dataset licensing program, and the publication of more than 400 workforce analytics reports.",
            '"Margaret has been central to ACPWB\'s intellectual identity for more than fifteen years," said Hendricks. "Her combination of methodological rigor, institutional knowledge, and commitment to the organization\'s public benefit mission makes her the clear and appropriate choice to lead ACPWB into its next chapter."',
            "Okafor holds advanced degrees in applied economics and organizational behavior and is a named inventor on four ACPWB patents relating to compensation methodology and survey administration. She has represented ACPWB at industry forums across North America and has testified before state legislative bodies on matters relating to pay transparency regulation.",
            '"Gerald built something genuinely important," said Okafor. "ACPWB\'s work has materially influenced how American organizations think about compensation fairness and disclosure. I am committed to deepening that impact and to ensuring that ACPWB continues to be the most trusted name in workforce equity research."',
            "Hendricks will serve in an advisory capacity through the end of 2025 to support the leadership transition.",
        ],
        'quote': "Margaret has been central to ACPWB's intellectual identity for more than fifteen years. Her combination of methodological rigor, institutional knowledge, and commitment to the organization's public benefit mission makes her the clear and appropriate choice.",
        'quote_attribution': 'Gerald Hendricks, Outgoing Chief Executive Officer',
        'contact': 'Media inquiries: communications@acpwb.com — (414) 667-5665',
    },
    {
        'slug': 'ai-compensation-intelligence-suite',
        'date': date(2025, 1, 22),
        'day': 22,
        'month': 1,
        'year': 2025,
        'headline': 'ACPWB Launches AI-Powered Compensation Intelligence Suite for Workforce Analytics Professionals',
        'subhead': 'The new platform applies large language model technology to ACPWB\'s proprietary compensation datasets, generating narrative summaries, peer group comparisons, and trend analyses described by early access participants as "largely coherent."',
        'body': [
            "MILWAUKEE, WI — The American Corporation for Public Well Being today announced the general availability of the ACPWB Compensation Intelligence Suite, a new artificial intelligence—powered platform that applies advanced language model technology to ACPWB's proprietary compensation benchmarking datasets.",
            "The Suite enables HR professionals, compensation analysts, and organizational leaders to generate narrative interpretations of complex workforce data, identify peer group positioning relative to market benchmarks, and produce board-ready summary documents — tasks that previously required subscription access to ACPWB's full advisory services tier.",
            "The platform leverages a fine-tuned language model trained on ACPWB's two-decade archive of compensation reports, governance frameworks, and workforce equity analyses, supplemented by current market benchmarking data updated on a quarterly basis. Outputs are generated within seconds and include embedded confidence intervals and a disclaimer noting that findings are “directionally indicative” and should not be construed as legal, financial, or compensation advice.",
            '"Artificial intelligence represents a meaningful opportunity to democratize access to compensation intelligence," said Margaret Okafor, Chief Research Officer at the time of the platform\'s development. "We have applied these capabilities with care, ensuring that the Suite reflects the methodological standards and interpretive discipline that ACPWB is known for."',
            'Early access participants from seventeen organizations provided feedback during a four-month pilot program. Participants reported that AI-generated compensation narratives were “largely coherent” and “saved meaningful time” compared to manual report interpretation. Three participants noted that the platform\'s tendency to recommend further study was “consistent with prior ACPWB deliverables.”',
            '"The feedback from our pilot cohort was instructive," said Diego Ramirez, Vice President of Client Strategy. "Seventeen organizations participated, and the consistent theme was that the AI-generated analyses helped teams reach the same conclusions they were already going to reach — but with substantially less effort. That is exactly what we designed for."',
            "The Compensation Intelligence Suite is available to ACPWB institutional partners as part of the organization's Enhanced Research Access tier. Individual researcher access will be made available in a subsequent release.",
        ],
        'quote': "We have applied these capabilities with care, ensuring that the Suite reflects the methodological standards and interpretive discipline that ACPWB is known for.",
        'quote_attribution': 'Margaret Okafor, Chief Research Officer',
        'contact': 'Media inquiries: communications@acpwb.com — (414) 667-5665',
    },
    {
        'slug': 'patent-12104455-employee-engagement',
        'date': date(2024, 10, 8),
        'day': 8,
        'month': 10,
        'year': 2024,
        'headline': 'United States Patent and Trademark Office Issues ACPWB Patent for Employee Engagement Survey Methodology',
        'subhead': "US Patent 12,104,455 B2 protects ACPWB's proprietary approach to administering engagement surveys in a manner designed to produce results consistent with prior years.",
        'body': [
            "MILWAUKEE, WI — The American Corporation for Public Well Being announced today that the United States Patent and Trademark Office has issued US Patent 12,104,455 B2, titled “Method for Administering an Employee Engagement Survey and Producing Results Consistent With Prior Years.” The patent was filed February 14, 2021 and issued October 1, 2024.",
            "The patent protects ACPWB's proprietary survey normalization methodology, which applies a statistically derived smoothing coefficient to raw engagement survey responses in order to reduce year-over-year variance and ensure that engagement trends appear stable and progressive across survey cycles.",
            "The inventors named on the patent are Okafor, A.; Wu, J.; and Hernandez, T., all members of ACPWB's Survey Methodology and Advanced Analytics division.",
            '"Employee engagement measurement is among the most consequential — and most frequently misrepresented — domains in organizational research," said a representative of the Survey Methodology division. "This patent reflects years of methodological development aimed at delivering survey results that are both defensible and reassuring."',
            "The issuance brings ACPWB's active patent portfolio to six United States patents spanning compensation benchmarking, data watermarking, executive peer group construction, governance certification, and workforce analytics visualization.",
            '"The normalization methodology at the core of this patent took nearly three years to refine to the point where results were both statistically defensible and reliably consistent with prior survey cycles," said Teresa Hernandez, Lead Survey Methodologist and co-inventor. "That those two objectives can be achieved simultaneously was, I will admit, not obvious at the outset of the research."',
            "The complete text of US Patent 12,104,455 B2 is publicly available through the USPTO database. ACPWB's full patent portfolio is described on the Patents page of this website.",
        ],
        'quote': "This patent reflects years of methodological development aimed at delivering survey results that are both defensible and reassuring.",
        'quote_attribution': 'ACPWB Survey Methodology & Advanced Analytics Division',
        'contact': 'Media inquiries: communications@acpwb.com — (414) 667-5665',
    },
    {
        'slug': '2024-compensation-transparency-award',
        'date': date(2024, 6, 3),
        'day': 3,
        'month': 6,
        'year': 2024,
        'headline': 'ACPWB Receives National Excellence in Compensation Transparency Award for Fifth Consecutive Year',
        'subhead': "The American Institute for Compensation Research and Adjacent Fields recognized ACPWB's sustained contributions to workforce pay equity research and publication.",
        'body': [
            "MILWAUKEE, WI — The American Corporation for Public Well Being has received the National Excellence in Compensation Transparency Award from the American Institute for Compensation Research and Adjacent Fields for the fifth consecutive year, the organization announced today.",
            "The annual award recognizes organizations that have demonstrated measurable commitment to advancing pay transparency practices, producing rigorous compensation benchmarking research, and contributing to the broader public discourse on workforce equity. ACPWB has received the award in each year of its existence as a recognized award category.",
            '"Receiving this recognition five years consecutively is a reflection of the consistency and quality that ACPWB brings to its research mission," said the ACPWB Executive Leadership Team. "Compensation transparency is not a trend — it is a prerequisite for a fair and functioning labor market, and we are proud to be recognized as a leader in advancing it."',
            "The 2024 award was presented at the American Institute's annual recognition dinner in Washington, D.C. ACPWB was selected from a field of organizations across the workforce analytics and HR research sectors. Selection criteria include research output volume, methodological transparency, public access to findings, and demonstrated impact on compensation policy discourse.",
            "ACPWB has received 37 industry and regional recognitions since 2008. The organization's complete awards history is published on the Awards page of this website.",
        ],
        'quote': "Compensation transparency is not a trend — it is a prerequisite for a fair and functioning labor market, and we are proud to be recognized as a leader in advancing it.",
        'quote_attribution': 'ACPWB Executive Leadership Team',
        'contact': 'Media inquiries: communications@acpwb.com — (414) 667-5665',
    },
]
