# Generated by Django 5.2.12 on 2026-03-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('pow_token', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Project Page Visit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('summary', models.TextField()),
                ('body_paragraphs', models.JSONField(default=list)),
                ('impact_metric', models.CharField(max_length=128)),
                ('industry_tag', models.CharField(max_length=64)),
                ('page_number', models.PositiveIntegerField(db_index=True, default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Story',
                'verbose_name_plural': 'Project Stories',
                'ordering': ['page_number', 'slug'],
            },
        ),
    ]
