#!/usr/bin/env python3
"""Download Inter variable font (latin) from Google Fonts and generate fonts.css."""
import re
import sys
import urllib.request
from pathlib import Path

FONTS_URL = "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

HERE = Path(__file__).resolve().parent.parent
FONT_DIR = HERE / "acpwb" / "static" / "fonts" / "inter"
CSS_OUT = HERE / "acpwb" / "static" / "css" / "fonts.css"

req = urllib.request.Request(FONTS_URL, headers={"User-Agent": UA})
with urllib.request.urlopen(req) as r:
    css = r.read().decode()

block_re = re.compile(
    r"/\*\s*([\w-]+)\s*\*/\s*"
    r"@font-face\s*\{[^}]*"
    r"src:\s*url\(([^)]+)\)[^}]*"
    r"unicode-range:\s*([^}]+)\}",
    re.DOTALL,
)

blocks = {m.group(1): (m.group(2).strip(), m.group(3).strip().rstrip(";"))
          for m in block_re.finditer(css)}

if "latin" not in blocks:
    print("ERROR: latin block not found in Google Fonts response", file=sys.stderr)
    sys.exit(1)

latin_url, latin_urange = blocks["latin"]

FONT_DIR.mkdir(parents=True, exist_ok=True)

fname = "inter-variable-latin.woff2"
dest = FONT_DIR / fname
print(f"Downloading {fname} ...", end=" ", flush=True)
req2 = urllib.request.Request(latin_url, headers={"User-Agent": UA})
with urllib.request.urlopen(req2) as r2:
    dest.write_bytes(r2.read())
print(f"✓ ({dest.stat().st_size:,} bytes)")

CSS_OUT.write_text(
    f"/* Inter variable font — self-hosted; generated by tools/download_fonts.py */\n"
    f"@font-face {{\n"
    f"  font-family: 'Inter';\n"
    f"  font-style: normal;\n"
    f"  font-weight: 100 900;\n"
    f"  font-display: swap;\n"
    f"  src: url('../fonts/inter/{fname}') format('woff2');\n"
    f"  unicode-range: {latin_urange};\n"
    f"}}\n"
)
print(f"Wrote {CSS_OUT}")
