#!/usr/bin/env python3
"""Download Inter font woff2 files from Google Fonts and generate fonts.css."""
import re
import sys
import urllib.request
from pathlib import Path

FONTS_URL = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap"
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

HERE = Path(__file__).resolve().parent.parent
FONT_DIR = HERE / "acpwb" / "static" / "fonts" / "inter"
CSS_OUT = HERE / "acpwb" / "static" / "css" / "fonts.css"

WEIGHTS = [400, 500, 600, 700, 800, 900]

req = urllib.request.Request(FONTS_URL, headers={"User-Agent": UA})
with urllib.request.urlopen(req) as r:
    css = r.read().decode()

# Parse all @font-face blocks
block_re = re.compile(
    r"/\*\s*([\w-]+)\s*\*/\s*"
    r"@font-face\s*\{[^}]*font-weight:\s*(\d+)[^}]*"
    r"src:\s*url\(([^)]+)\)[^}]*"
    r"unicode-range:\s*([^}]+)\}",
    re.DOTALL,
)

# Collect blocks: (subset, weight, url, unicode_range)
blocks = []
for m in block_re.finditer(css):
    subset, weight, url, urange = m.group(1), int(m.group(2)), m.group(3).strip(), m.group(4).strip().rstrip(";")
    blocks.append((subset, weight, url, urange))

# We want all subsets (cyrillic-ext, cyrillic, greek-ext, greek, vietnamese, latin-ext, latin)
# Group by weight, preserving subset order
from collections import defaultdict
by_weight = defaultdict(list)
for subset, weight, url, urange in blocks:
    by_weight[weight].append((subset, url, urange))

FONT_DIR.mkdir(parents=True, exist_ok=True)

# Download woff2 for each weight+subset, collect for CSS
face_data = []  # list of (weight, subset, filename, unicode_range)
for weight in WEIGHTS:
    subsets = by_weight.get(weight, [])
    if not subsets:
        print(f"WARNING: no data for weight {weight}", file=sys.stderr)
        continue
    for subset, url, urange in subsets:
        fname = f"inter-{weight}-{subset}.woff2"
        dest = FONT_DIR / fname
        print(f"  [{weight}/{subset}] {fname} ...", end=" ", flush=True)
        req2 = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req2) as r2:
            dest.write_bytes(r2.read())
        print(f"✓ ({dest.stat().st_size:,} bytes)")
        face_data.append((weight, subset, fname, urange))

# Generate fonts.css with @font-face blocks
lines = ["/* Inter — self-hosted; generated by tools/download_fonts.py */\n"]
for weight, subset, fname, urange in face_data:
    lines.append(f"/* {subset} */")
    lines.append("@font-face {")
    lines.append("  font-family: 'Inter';")
    lines.append("  font-style: normal;")
    lines.append(f"  font-weight: {weight};")
    lines.append("  font-display: swap;")
    lines.append(f"  src: url('../fonts/inter/{fname}') format('woff2');")
    lines.append(f"  unicode-range: {urange};")
    lines.append("}")
    lines.append("")

CSS_OUT.write_text("\n".join(lines))
print(f"\nWrote {CSS_OUT} ({len(face_data)} @font-face blocks)")
